/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2019-02-16 18:33:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JSP.Form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class categoryManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--END GLOBAL STYLES -->\r\n");
      out.write("\r\n");
      out.write("    <!-- PAGE LEVEL STYLES -->\r\n");
      out.write("    <link href=\"library/assets/plugins/dataTables/dataTables.bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/plugins/bootstrap/css/bootstrap.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/css/main.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/css/theme.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/css/MoneAdmin.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/plugins/Font-Awesome/css/font-awesome.css\" />\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"library/assets/plugins/validationengine/css/validationEngine.jquery.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("#menu3{\r\n");
      out.write("\tbackground: #E05400;\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 3%, #E05400 30%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg_heading {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    margin-top: -32px;\r\n");
      out.write("    margin-left: 135px;\r\n");
      out.write("    font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"search\"]{\r\n");
      out.write("height:30px !important;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"]{\r\n");
      out.write("height:25px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("#successMessage{\r\n");
      out.write("\tmargin-left: 450px;\r\n");
      out.write("    z-index: 20000;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    color: green;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<script src='JS/complaints/searchComplaints.js'></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("var categorylist = \"\";\r\n");
      out.write("$('#dataTables-example input:checkbox').each(function(){\r\n");
      out.write("\t categorylist =  categorylist +\",\"+$(this).closest('tr').find('td:nth-child(3)').text();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function validateAddForm() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar categoryName = $(\"#categoryNameId\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tvar inputVal = new Array(categoryName);\r\n");
      out.write("\r\n");
      out.write("\t$('.error').hide();\r\n");
      out.write("\tflag = true;\r\n");
      out.write("\tfor (i = 0; i < inputVal.length; i++) {\r\n");
      out.write("\t\tif (inputVal[i].val() == \"\") {\r\n");
      out.write("\t\t\tinputVal[i]\r\n");
      out.write("\t\t\t\t\t.after('<span class=\"error\"> This field is required. </span>');\r\n");
      out.write("\t\t\tinputVal[i].focus();\r\n");
      out.write("\t\t\tflag = false;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if (inputVal[i].attr('id') == 'categoryNameId' && inputVal[i].val().length > 1) {\r\n");
      out.write("\t\t\tif(categorylist.indexOf(inputVal[i].val())>-1){\r\n");
      out.write("\t\t\t  inputVal[i].after('<span class=\"error\"> Please enter unique Category Name. </span>');\r\n");
      out.write("\t\t\t  inputVal[i].focus();\r\n");
      out.write("\t\t\t  flag = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\treturn flag;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validateEditForm() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar editCategoryName = $(\"#editCategoryNameId\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tvar inputVal = new Array(editCategoryName);\r\n");
      out.write("\r\n");
      out.write("\t$('.error').hide();\r\n");
      out.write("\tflag = true;\r\n");
      out.write("\tfor (i = 0; i < inputVal.length; i++) {\r\n");
      out.write("\t\tif (inputVal[i].val() == \"\") {\r\n");
      out.write("\t\t\tinputVal[i]\r\n");
      out.write("\t\t\t\t\t.after('<span class=\"error\"> This field is required. </span>');\r\n");
      out.write("\t\t\tinputVal[i].focus();\r\n");
      out.write("\t\t\tflag = false;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if (inputVal[i].attr('id') == 'editCategoryNameId' && inputVal[i].val().length > 1) {\r\n");
      out.write("\t\t\tif(categorylist.indexOf(inputVal[i].val())>-1){\r\n");
      out.write("\t\t\t  inputVal[i].after('<span class=\"error\"> Please enter unique Category Name. </span>');\r\n");
      out.write("\t\t\t  inputVal[i].focus();\r\n");
      out.write("\t\t\t  flag = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\treturn flag;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#all\").click(function(){\r\n");
      out.write("    $('#dataTables-example input:checkbox').not(this).prop('checked', this.checked);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#dataTables-example input:checkbox').click(function(){\r\n");
      out.write("var numberOfChecked = $('#dataTables-example input:checkbox:checked').length;\r\n");
      out.write("\r\n");
      out.write("var numberOfCheckbox = $('#dataTables-example input:checkbox').length;\r\n");
      out.write("if(numberOfChecked==(numberOfCheckbox-1)){\r\n");
      out.write("\t $('#all').prop('checked', this.checked);\r\n");
      out.write("}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#addCategory').click(function(){\r\n");
      out.write("\t\t$(\".ui-dialog-content\").dialog(\"close\");\r\n");
      out.write("\t\t$( \"#addDialog\" ).dialog({ 'width':'500px','modal':'true'});\r\n");
      out.write("\t}); \r\n");
      out.write("$('#editCategory').click(function(){\r\n");
      out.write("\t$(\".ui-dialog-content\").dialog(\"close\");\r\n");
      out.write("\tvar numberOfChecked = $('#dataTables-example td input:checkbox:checked').length;\r\n");
      out.write("\tif(numberOfChecked==1){\r\n");
      out.write("\t$( \"#editDialog\" ).dialog({ 'width':'500px','modal':'true'});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#dataTables-example td input:checkbox:checked').each(function(){\r\n");
      out.write("\t\t$('#editCategoryId').val($(this).closest('tr').find('td:nth-child(1)').find('input[type=\"checkbox\"]').attr('id').trim());\r\n");
      out.write("\t\t$('#editCategoryNameId').val($(this).closest('tr').find('td:nth-child(3)').text());\r\n");
      out.write("\t\t$('#editCategoryDescId').val($(this).closest('tr').find('td:nth-child(4)').text());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcategorylist = categorylist.replace($(this).closest('tr').find('td:nth-child(3)').text().trim(),\"\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\talert(\"Please select only one Category to Edit\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}); \r\n");
      out.write("$('.closeBtn,.imgClose').click(function(){\r\n");
      out.write("\t$(\".ui-dialog-content\").dialog(\"close\");\r\n");
      out.write("\t\r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#categorySaveBtnId').click(function(){\r\n");
      out.write("\tif(validateAddForm()){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"addCategory.do\",\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\t\t'categoryName':$('#categoryNameId').val(),\r\n");
      out.write("\t\t\t'categoryDesc':$('#categoryDescId').val()},\r\n");
      out.write("\t\tsuccess:function(response){\r\n");
      out.write("\t\t\talert(response);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\twindow.location.reload();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#editCategoryBtn').click(function(){\r\n");
      out.write("\tif(validateEditForm()){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"editCategory.do\",\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\t\t'categoryId':$('#editCategoryId').val(),\r\n");
      out.write("\t\t\t'categoryName':$('#editCategoryNameId').val(),\r\n");
      out.write("\t\t\t'categoryDesc':$('#editCategoryDescId').val()},\r\n");
      out.write("\t\tsuccess:function(response){\r\n");
      out.write("\t\t\talert(response);\r\n");
      out.write("\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#deleteCategory').click(function(){\r\n");
      out.write("\tvar categoryList = \"\";\r\n");
      out.write("\tvar categoryNameList = \"\";\r\n");
      out.write("\t$('#dataTables-example input:checkbox:checked').each(function(){\r\n");
      out.write("\t\tif($(this).closest('tr').find('td:nth-child(1)').find('input[type=\"checkbox\"]').attr('id')!=undefined){\r\n");
      out.write("\t\t  categoryList = categoryList +\",\"+$(this).closest('tr').find('td:nth-child(1)').find('input[type=\"checkbox\"]').attr('id').trim();\r\n");
      out.write("\t\t  categoryNameList = categoryNameList +\",\"+$(this).closest('tr').find('td:nth-child(3)').text().trim();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tif(confirm(\"Are you sure want to Delete these Category \"+categoryNameList.substring(1)+\" ? \")){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"deleteCategory.do\",\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\t\t'categoryId':categoryList.substring(1)},\r\n");
      out.write("\t\tsuccess:function(response){\r\n");
      out.write("\t\t\talert(response);\r\n");
      out.write("\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class='table-bordered table table-striped display'\r\n");
      out.write("\tstyle='width: 100%; font-size: 28px;'>\r\n");
      out.write("<tr>\r\n");
      out.write("\t\t<td colspan='8'>\r\n");
      out.write("\t\t\t<a href=\"#\" style=\"padding: 10px;background-color: #78C948;color:white;\" id=\"addCategory\">Add Category</a>\r\n");
      out.write("\t\t\t<a style=\"padding: 10px;background-color: #FEBA17;color:white;\" id=\"editCategory\">Edit</a>\r\n");
      out.write("\t\t\t<a style=\"padding: 10px;background-color: #EE3B41;color:white;\" id=\"deleteCategory\">Delete</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           <div id=\"content\" style=\"margin-left: 0px !important\">\r\n");
      out.write("<div id=\"successMessage\"></div>\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"panel panel-default\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-striped table-bordered table-hover\" id=\"dataTables-example\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                           <!--  <th style=\"color:black !important\"></th> -->\r\n");
      out.write("                                            <th style=\"color:black !important\"><input type=\"checkbox\" id=\"all\" style=\"width:15px;\"/></th>\r\n");
      out.write("                                            <th style=\"color:black !important\"><b> #</b></th>\r\n");
      out.write("                                            <th style=\"color:black !important\"><b>Category Name</b></th>\r\n");
      out.write("                                            <th style=\"color:black !important\"><b>Description</b></th>\r\n");
      out.write("                                           \r\n");
      out.write("                                        \r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                   \r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                     ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                          \r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"addDialog\" style=\"display: none;\">\r\n");
      out.write("\r\n");
      out.write("<img class=\"imgClose\" src=\"library/img/Close_SMS.png\"\r\n");
      out.write("\t\t\tstyle=\"width: 40px; border-width: 0px; float: right; margin-top: -43px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t<h2 class=\"bg_heading\">Add New Category</h2>\r\n");
      out.write("<span><b>Category Name:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"categoryNameId\" name=\"categoryName\" style=\"margin-left:35px;\"/><br/>\r\n");
      out.write("<span><b>Category Description:</b></span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"categoryDescId\" name=\"categoryDesc\" style=\"margin-left: 5px;\"/><br/>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"Save\" id=\"categorySaveBtnId\"/> <input type=\"button\" value=\"Close\"  class=\"closeBtn\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"editDialog\" style=\"display: none;\">\r\n");
      out.write("\r\n");
      out.write("<img class=\"imgClose\" src=\"library/img/Close_SMS.png\"\r\n");
      out.write("\t\t\tstyle=\"width: 40px; border-width: 0px; float: right; margin-top: -43px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t<h2 class=\"bg_heading\">Edit Category</h2>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"editCategoryId\"/>\r\n");
      out.write("<span><b>Category Name:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"editCategoryNameId\" name=\"editCategoryName\" style=\"margin-left:43px;\" /><br/>\r\n");
      out.write("<span><b>Category Description:</b></span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"editCategoryDescId\" name=\"editCategoryDesc\" style=\"margin-left: 13px;\"/><br/>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"Update\" id=\"editCategoryBtn\"/> <input type=\"button\" value=\"Close\" class=\"closeBtn\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"assets/plugins/dataTables/jquery.dataTables.js\"></script>\r\n");
      out.write("    <script src=\"assets/plugins/dataTables/dataTables.bootstrap.js\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("         $(document).ready(function () {\r\n");
      out.write("             $('#dataTables-example').dataTable();\r\n");
      out.write("         });\r\n");
      out.write("    </script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/JSP/Form/categoryManagement.jsp(285,37) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/JSP/Form/categoryManagement.jsp(285,37) '${list.categoryDtl}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list.categoryDtl}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/JSP/Form/categoryManagement.jsp(285,37) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("app");
    // /WEB-INF/views/JSP/Form/categoryManagement.jsp(285,37) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("count");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          \r\n");
          out.write("                                               <tr class=\"odd gradeX\">\r\n");
          out.write("          \t\t\t\t\t\t\t\t\r\n");
          out.write("          \t\t\t\t\t\t\t\r\n");
          out.write("                                            <td><input type=\"checkbox\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getCategoryId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" style=\"width:15px;\"/></td>\r\n");
          out.write("                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                             <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getCategoryName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                             <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getCategoryDesc()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                           \r\n");
          out.write("                                           \r\n");
          out.write("                                        </tr>\t\r\n");
          out.write("          \r\n");
          out.write("          \t\t\t\t\t\t\t ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
