/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2019-02-15 17:22:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JSP.Form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class checkApplicationStatus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http//www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <script src=\"library/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write(" <link href=\"library/css/style.css\" rel=\"stylesheet\"/> \r\n");
      out.write("\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"library/assets/plugins/bootstrap/css/bootstrap.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/css/main.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/theme.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/MoneAdmin.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/plugins/Font-Awesome/css/font-awesome.css\" />\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"assets/plugins/validationengine/css/validationEngine.jquery.css\" />\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<link href=\"library/css/jquery-ui-1.8.21.custom.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* \r\n");
      out.write("tr:nth-child(even) {background: white;height:40px;}\r\n");
      out.write("tr:nth-child(odd) {background:#EDEDED ;height:40px;} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("input[type=\"button\"] {\r\n");
      out.write("    border-radius 10px;\r\n");
      out.write("    background-color #2DAAE1;\r\n");
      out.write("    font-weight bold;\r\n");
      out.write("    cursor pointer;\r\n");
      out.write("    padding 5px 5px 5px 5px;\r\n");
      out.write("    margin-left150px; \r\n");
      out.write("    width 100px;\r\n");
      out.write("    color white;\r\n");
      out.write("    margin-top 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myTable td{\r\n");
      out.write("padding-left:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myTable td span{\r\n");
      out.write("margin-left:10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tvar isStatusButtonClicked = localStorage.getItem('isStatusButtonClicked');\r\n");
      out.write("\tvar isDetailButtonClicked = localStorage.getItem('isDetailButtonClicked');\r\n");
      out.write("\t\r\n");
      out.write("\tif(isStatusButtonClicked != 'null'){\r\n");
      out.write("\t\t$('#detailsHeader').css({'display':'none'});\r\n");
      out.write("\t\t$('#myTable').css({'display':'none'});\r\n");
      out.write("\t\t$('#statusHeader').css({'display':'table'});\r\n");
      out.write("\t\t$('#statusTable').css({'display':'table'});\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t$('#statusHeader').css({'display':'none'});\r\n");
      out.write("\t\t$('#statusTable').css({'display':'none'});\r\n");
      out.write("\t}\r\n");
      out.write("\tif(isDetailButtonClicked != 'null'){\r\n");
      out.write("\t\t$('#statusHeader').css({'display':'none'});\r\n");
      out.write("\t\t$('#statusTable').css({'display':'none'});\r\n");
      out.write("\t\t$('#detailsHeader').css({'display':'table'});\r\n");
      out.write("\t\t$('#myTable').css({'display':'table'});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t$('#detailsHeader').css({'display':'none'});\r\n");
      out.write("\t\t$('#myTable').css({'display':'none'});\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#apprefbtn').click(function(){\r\n");
      out.write("\t\tif($('#appref').val().length==0){\r\n");
      out.write("\t\t\talert(\"Please enter Application Ref\");\r\n");
      out.write("\t\t\t$('#appref').focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t localStorage.setItem('isStatusButtonClicked', true);\r\n");
      out.write("\t\t localStorage.setItem('isDetailButtonClicked', null);\r\n");
      out.write("\t\twindow.location.href=\"checkApplicationStatus.do?appId=\"+$('#appref').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#appdetailbtn').click(function(){\r\n");
      out.write("\t\tif($('#appref').val().length==0){\r\n");
      out.write("\t\t\talert(\"Please enter Application Ref\");\r\n");
      out.write("\t\t\t$('#appref').focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t localStorage.setItem('isDetailButtonClicked', true);\r\n");
      out.write("\t\t localStorage.setItem('isStatusButtonClicked', null);\r\n");
      out.write("\t\t window.location.href=\"checkApplicationStatus.do?appId=\"+$('#appref').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#withdrawAppbtn').click(function(){\r\n");
      out.write("\t\tif($('#appref').val().length==0){\r\n");
      out.write("\t\t\talert(\"Please enter Application Ref\");\r\n");
      out.write("\t\t\t$('#appref').focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(confirm(\"Are you sure want to withdraw?\")){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"withdrawApp.do\",\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tdata:{'appId':$('#appref').val()},\r\n");
      out.write("\t\t\tsuccess:function(response){\r\n");
      out.write("\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table align=\"center\" style=\"width:90%; font-size: 28px;\">\r\n");
      out.write("\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<tr><td valign=\"middle\"> \r\n");
      out.write("<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t<td valign=\"middle\" colspan=\"2\" style=\"height: 130px; width: 100%;\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" align=\"center\"><img src=\"library/img/twad_logo.gif\" width=\"110px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"106px\" style=\"margin-left: 50px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"50%\" align=\"center\"><img src=\"library/img/middleImage.png\" width=\"560px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"67px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td  width=\"25%\" align=\"center\"><img src=\"library/img/pic6_2.jpg\" width=\"130px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"130px\" style=\"margin-right: 50px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("  </td></tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"padding: 0px; width: 100%;\">\r\n");
      out.write("                <div style=\"background-image: url(library/img/border_bg.jpg); height: 7px; background-repeat: repeat-x;\">\r\n");
      out.write("                    &nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("</tbody></table>\t\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<table style=\"width:100%;height: 100px;\"><tbody>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"text-align: center; background-color: #FCFCF4; font-size: 17px; height: 10px; color: #800000; font-weight: bold;\"> Application Ref: <input type=\"text\" id=\"appref\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\"><input type=\"button\" id=\"apprefbtn\" value=\"Get Application Status\"/> <input type=\"button\" id=\"appdetailbtn\" style=\"margin-left:40px;\" value=\"View Application Details\"/><!-- <input type=\"button\" id=\"withdrawAppbtn\" style=\"margin-left:10px;\" value=\"Withdraw Application\"/> --><a href=\"/TwadWeb/index.do\" style=\"margin-left:10px;\">Back to Home Page </a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("</tbody></table>\r\n");
      out.write("<table id=\"statusHeader\" class=\"table-bordered table table-striped display\" style=\"width: 100%; font-size: 28px;display:none;\">\r\n");
      out.write("\r\n");
      out.write("\t<tbody><tr>\r\n");
      out.write("\t\t<td style=\"text-align: center; background-color: #FCFCF4; font-size: 17px; height: 10px; color: #800000; font-weight: bold;\">Application Status ( ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getAppId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" )</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("</tbody></table>\r\n");
      out.write("<table id=\"statusTable\" align=\"center\" class=\"table-bordered table table-striped display\" style=\"width: 50%;display:none;\">\r\n");
      out.write("<tbody>\r\n");
      out.write("\r\n");
      out.write("<tr><td width=\"50%\"><b>Application Status</b></td><td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getCeStatus()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td></tr>\r\n");
      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<table id=\"detailsHeader\" class=\"table-bordered table table-striped display\" style=\"width: 100%; font-size: 28px;display:none;\">\r\n");
      out.write("\r\n");
      out.write("\t<tbody><tr>\r\n");
      out.write("\t\t<td style=\"text-align: center; background-color: #FCFCF4; font-size: 17px; height: 10px; color: #800000; font-weight: bold;\">Application Details</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("</tbody></table>\r\n");
      out.write("\r\n");
      out.write("\t<table id=\"myTable\" width=\"100%\" style=\"display:none;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t\t<td width=\"25%\"><b>Application #</b></td>\r\n");
      out.write("\t\t\t<td width=\"25%\">:<span id=\"legCompNameId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getAppId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td width=\"25%\"><b>Registered</b></td>\r\n");
      out.write("\t\t\t<td width=\"25%\">:<span id=\"dateId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getCreateDate()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"25%\"><b>Legal Name of Company</b></td>\r\n");
      out.write("\t\t\t<td width=\"25%\">:<span id=\"legCompNameId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getLegCompName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td width=\"25%\"><b>Name of contact person</b></td>\r\n");
      out.write("\t\t\t<td width=\"25%\">:<span id=\"contactPersonNameId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getSalutation()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getContactPersonName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>Address for Correspondence</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"correspondenceAddrId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getCdoorNo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getCplotNo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getCstreetName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getClocation()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getCpinCode()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td><b>Site Address</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"addrPremSoughtId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getDoorNo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getPlotNo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getStreetName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getLocation()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getPinCode()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>Mobile Number</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"mobileNumId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getMobileNum()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td><b>Land line number</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"landlineNumId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getLandLineNo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>Email Id</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"emailAddrId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getEmailAddr()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td><b>Web Address</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"webAddressId\">\r\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getWebAddress()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><b>Is this New Connection?</b></td>\r\n");
      out.write("\t\t\t<td>:<span class=\"lessWidth\" id=\"isNewConnectionId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getIsNewConnection()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td><b>Is this an alteration to the existing water/ sewer\r\n");
      out.write("\t\t\t\t\tconnection?</b></td>\r\n");
      out.write("\t\t\t<td>:<span class=\"lessWidth\"\r\n");
      out.write("\t\t\t\tid=\"isExistConnectionForAlterationId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getIsExistConnectionForAlteration()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>Is this a reconnection of service connection for\r\n");
      out.write("\t\t\t\t\texisting Connection?</b></td>\r\n");
      out.write("\t\t\t<td>:<span class=\"lessWidth\" id=\"isReconnectionForServiceId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.isReconnectionForService}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span class=\"moreWidth\" id=\"reconnectionTypeId\">,&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.reconnectionType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><b>Requirement of water in MLD (Million Litres per day)</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"reqMldId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getReqMld()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>CMWSSB Area Number/ Chennai Corporation Zone Number</b></td>\r\n");
      out.write("\t\t\t<td style=\"\">:<span class=\"lessWidth\" id=\"cmwssbZoneNumId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getCmwssbZoneNum()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td><b>Division No./Depot No</b></td>\r\n");
      out.write("\t\t\t<td style=\"\">:<span id=\"divId\" style=\"\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getDivId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>Bill No. given by Corporation/ Local Authority</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"billNumId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getBillNo2()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getBillNo1()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td><b>Annual Assessment value of property fixed by Chennai\r\n");
      out.write("\t\t\t\t\tCorporation/ Local authority</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"annAssmtValId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getAnnAssmtVal()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>Whether internal plumbing works are completed</b></td>\r\n");
      out.write("\t\t\t<td>:<span class=\"lessWidth\" id=\"intrPlumStatusId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getIntrPlumStatus()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><b>Whether water/ sewer line is available near the\r\n");
      out.write("\t\t\t\t\tproperty</b></td>\r\n");
      out.write("\t\t\t<td>:<span class=\"lessWidth\" id=\"watSevPropId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getWatSevProp()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>Work Type</b></td>\r\n");
      out.write("\t\t\t<td>:<span class=\"lessWidth\" id=\"workTypeId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getWorkType()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td><b>Type of category</b></td>\r\n");
      out.write("\t\t\t<td style=\"\">:<span class=\"classCategory\" id=\"categoryTypeId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getCategoryType()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><b>Payment Type</b></td>\r\n");
      out.write("\t\t\t<td>:<span class=\"lessWidth\" id=\"paymentTypeId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getPaymentType()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td><b>DD Number</b></td>\r\n");
      out.write("\t\t\t<td>:<span id=\"ddNumId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.application.getDdNum()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"4\" align=\"center\"><input type=\"button\"\r\n");
      out.write("\t\t\t\tid=\"printbtnId\" onclick=\"javascript:window.print();\"\r\n");
      out.write("\t\t\t\tname=\"industrialistSubmitBtn\" value=\"Print\" /></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</body>\r\n");
      out.write("\t\t\t</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
