/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2019-02-16 18:33:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JSP.Form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class districtTalukManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--END GLOBAL STYLES -->\r\n");
      out.write("\r\n");
      out.write("    <!-- PAGE LEVEL STYLES -->\r\n");
      out.write("    <link href=\"library/assets/plugins/dataTables/dataTables.bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/plugins/bootstrap/css/bootstrap.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/css/main.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/css/theme.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/css/MoneAdmin.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"library/assets/plugins/Font-Awesome/css/font-awesome.css\" />\r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"library/assets/plugins/validationengine/css/validationEngine.jquery.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("#menu3{\r\n");
      out.write("\tbackground: #E05400;\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 3%, #E05400 30%);\r\n");
      out.write("}\r\n");
      out.write("input[type=\"search\"]{\r\n");
      out.write("height:30px !important;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"]{\r\n");
      out.write("height:25px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg_heading {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    margin-top: -32px;\r\n");
      out.write("    margin-left: 135px;\r\n");
      out.write("    font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".error {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("#successMessage{\r\n");
      out.write("\tmargin-left: 450px;\r\n");
      out.write("    z-index: 20000;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    color: green;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<script src='JS/complaints/searchComplaints.js'></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("var taluklist = \"\";\r\n");
      out.write("var districtNameList = \"\";\r\n");
      out.write("$('#dataTables-example input:checkbox').each(function(){\r\n");
      out.write("\tdistrictNameList =  districtNameList +\",\"+$(this).closest('tr').find('td:nth-child(3)').text();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#dataTables-example input:checkbox').each(function(){\r\n");
      out.write("\t taluklist =  taluklist +\",\"+$(this).closest('tr').find('td:nth-child(4)').text();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function validateAddDistrictForm() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar districtName = $(\"#districtNameId\");\r\n");
      out.write("\tvar talukNo = $(\"#clonedDiv .talukNo\");\r\n");
      out.write("\t/* var talukAddr = $(\"#clonedDiv .talukAddr\");\r\n");
      out.write("\tvar talukMobile = $(\"#clonedDiv .talukMobile\"); */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tvar inputVal = new Array(districtName,talukNo/* ,talukAddr,talukMobile */);\r\n");
      out.write("\r\n");
      out.write("\t$('.error').hide();\r\n");
      out.write("\tflag = true;\r\n");
      out.write("\tvar reg = /^[0-9]+$/;\r\n");
      out.write("\tfor (i = 0; i < inputVal.length; i++) {\r\n");
      out.write("\t\r\n");
      out.write("\t\t $(inputVal[i]).each(function(){\r\n");
      out.write("\t\t\t if ($(this).val() == \"\") {\r\n");
      out.write("\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t.after('<span class=\"error\"> This field is required. </span>');\r\n");
      out.write("\t\t\t\t\t$(this).focus();\r\n");
      out.write("\t\t\t\t\tflag = false;\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t else  if ($(this).attr('id') == 'districtNameId' && $(this).val().length > 1) {\r\n");
      out.write("\t\t\t\t\tif(districtNameList.indexOf($(this).val())>-1){\r\n");
      out.write("\t\t\t\t\t\t  $(this).after('<span class=\"error\"> Please enter unique District Name. </span>');\r\n");
      out.write("\t\t\t\t\t\t  $(this).focus();\r\n");
      out.write("\t\t\t\t\t\t  flag = false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t else  if ($(this).attr('class') == 'talukNo' && (!reg.test($(this).val()) || taluklist.indexOf(\",\"+$(this).val()+\",\")>-1)) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  $(this).after('<span class=\"error\"> Please enter unique Taluk No. and should be Numeric </span>');\r\n");
      out.write("\t\t\t\t\t\t  $(this).focus();\r\n");
      out.write("\t\t\t\t\t\t  flag = false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*  else if ($(this).attr('class') == 'talukMobile' && !/^[0-9]{10}$/.test($(this).val())) {\r\n");
      out.write("\t\t\t\t$(this).after('<span class=\"error\"> Please enter correct mobile No. </span>');\r\n");
      out.write("\t\t\t\t$(this).focus();\r\n");
      out.write("\t\t\t\tflag = false;\r\n");
      out.write("\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\treturn flag;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateAddTalukForm() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar districtName = $(\"#talukDistrictId\");\r\n");
      out.write("\tvar talukNo = $(\"#talukClonedDiv .talukNo\");\r\n");
      out.write("\t/* var talukAddr = $(\"#talukClonedDiv .talukAddr\");\r\n");
      out.write("\tvar talukMobile = $(\"#talukClonedDiv .talukMobile\"); */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tvar inputVal = new Array(districtName,talukNo/* ,talukAddr,talukMobile */);\r\n");
      out.write("\r\n");
      out.write("\t$('.error').hide();\r\n");
      out.write("\tflag = true;\r\n");
      out.write("\tvar reg = /^[0-9]+$/;\r\n");
      out.write("\tfor (i = 0; i < inputVal.length; i++) {\r\n");
      out.write("\t\r\n");
      out.write("\t\t $(inputVal[i]).each(function(){\r\n");
      out.write("\t\t\t if ($(this).val() == \"\") {\r\n");
      out.write("\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t.after('<span class=\"error\"> This field is required. </span>');\r\n");
      out.write("\t\t\t\t\t$(this).focus();\r\n");
      out.write("\t\t\t\t\tflag = false;\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t else  if ($(this).attr('class') == 'talukNo' && taluklist.indexOf(\",\"+$(this).val()+\",\")>-1) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  $(this).after('<span class=\"error\"> Please enter unique Taluk Name </span>');\r\n");
      out.write("\t\t\t\t\t\t  $(this).focus();\r\n");
      out.write("\t\t\t\t\t\t  flag = false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*  else if ($(this).attr('class') == 'talukMobile' && !/^[0-9]{10}$/.test($(this).val())) {\r\n");
      out.write("\t\t\t\t$(this).after('<span class=\"error\"> Please enter correct mobile No. </span>');\r\n");
      out.write("\t\t\t\t$(this).focus();\r\n");
      out.write("\t\t\t\tflag = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write(" */\t\t\t\t\t\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\treturn flag;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validateEditForm() {\r\n");
      out.write("\treturn true;\r\n");
      out.write("\t\r\n");
      out.write("\tvar editTalukNo = $(\"#editTalukNoId\");\r\n");
      out.write("\t/* var editTalukAddr = $(\"#editTalukAddrId\");\r\n");
      out.write("\tvar editTalukMobile = $(\"#editTalukMobileId\"); */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tvar inputVal = new Array(editTalukNo/* ,editTalukAddr,editTalukMobile */);\r\n");
      out.write("\r\n");
      out.write("\t$('.error').hide();\r\n");
      out.write("\tflag = true;\r\n");
      out.write("\tfor (i = 0; i < inputVal.length; i++) {\r\n");
      out.write("\t\tif (inputVal[i].val() == \"\") {\r\n");
      out.write("\t\t\tinputVal[i]\r\n");
      out.write("\t\t\t\t\t.after('<span class=\"error\"> This field is required. </span>');\r\n");
      out.write("\t\t\tinputVal[i].focus();\r\n");
      out.write("\t\t\tflag = false;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t else  if (inputVal[i].attr('id') == 'editTalukNoId' && taluklist.indexOf(\",\"+inputVal[i].val()+\",\")>-1) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t  inputVal[i].after('<span class=\"error\"> Please enter unique Taluk Name </span>');\r\n");
      out.write("\t\t\t  inputVal[i].focus();\r\n");
      out.write("\t\t\t  flag = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("/* \r\n");
      out.write("else if (inputVal[i].attr('id') == 'editTalukMobileId' && !/^[0-9]{10}$/.test(inputVal[i].val())) {\r\n");
      out.write("\tinputVal[i].after('<span class=\"error\"> Please enter correct mobile No. </span>');\r\n");
      out.write("\tinputVal[i].focus();\r\n");
      out.write("\tflag = false;\r\n");
      out.write("}\r\n");
      out.write("\t */\t\r\n");
      out.write("\t}\r\n");
      out.write("\treturn flag;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#all\").click(function(){\r\n");
      out.write("    $('#dataTables-example input:checkbox').not(this).prop('checked', this.checked);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#dataTables-example input:checkbox').click(function(){\r\n");
      out.write("var numberOfChecked = $('#dataTables-example input:checkbox:checked').length;\r\n");
      out.write("\r\n");
      out.write("var numberOfCheckbox = $('#dataTables-example input:checkbox').length;\r\n");
      out.write("if(numberOfChecked==(numberOfCheckbox-1)){\r\n");
      out.write("\t $('#all').prop('checked', this.checked);\r\n");
      out.write("}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#addDistrict').click(function(){\r\n");
      out.write("\t\t$(\".ui-dialog-content\").dialog(\"close\");\r\n");
      out.write("\t\t$( \"#addDialog\" ).dialog({ 'width':'500px','modal':'true'});\r\n");
      out.write("\t}); \r\n");
      out.write("\r\n");
      out.write("$('#addTaluk').click(function(){\r\n");
      out.write("\t$(\".ui-dialog-content\").dialog(\"close\");\r\n");
      out.write("\t$( \"#addTalukDialog\" ).dialog({ 'width':'500px','modal':'true'});\r\n");
      out.write("}); \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("$('#editTaluk').click(function(){\r\n");
      out.write("\t$(\".ui-dialog-content\").dialog(\"close\");\r\n");
      out.write("\tvar numberOfChecked = $('#dataTables-example td input:checkbox:checked').length;\r\n");
      out.write("\tif(numberOfChecked==1){\r\n");
      out.write("\t$( \"#editDialog\" ).dialog({ 'width':'500px','modal':'true'});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#dataTables-example td input:checkbox:checked').each(function(){\r\n");
      out.write("\t\t$('#editTalukId').val($(this).closest('tr').find('td:nth-child(1)').find('input[type=\"checkbox\"]').attr('id').trim());\r\n");
      out.write("\t\t$('#editDistrictNameId').val($(this).closest('tr').find('td:nth-child(3)').text());\r\n");
      out.write("\t\t$('#editTalukNoId').val($(this).closest('tr').find('td:nth-child(4)').text());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* $('#editTalukAddrId').val($(this).closest('tr').find('td:nth-child(5)').text());\r\n");
      out.write("\t\t$('#editTalukPhoneId').val($(this).closest('tr').find('td:nth-child(6)').text());\r\n");
      out.write("\t\t$('#editTalukMobileId').val($(this).closest('tr').find('td:nth-child(7)').text());\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tdistrictNameList = districtNameList.replace($(this).closest('tr').find('td:nth-child(3)').text().trim(),\"\");\r\n");
      out.write("\t\ttaluklist = taluklist.replace($(this).closest('tr').find('td:nth-child(4)').text().trim(),\"\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\talert(\"Please select only one Taluk to Edit\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}); \r\n");
      out.write("$('.closeBtn,.imgClose').click(function(){\r\n");
      out.write("\t$(\".ui-dialog-content\").dialog(\"close\");\r\n");
      out.write("\t\r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#talukSaveBtnId').click(function(){\r\n");
      out.write("\tvar districtTalukIds = \"\";\r\n");
      out.write("\t/* var districtTalukAddrs = \"\";\r\n");
      out.write("\tvar districtTalukPhones = \"\";\r\n");
      out.write("\tvar districtTalukMobiles = \"\"; */\r\n");
      out.write("\t $('#clonedDiv .talukNo').each(function(){\r\n");
      out.write("\t\t districtTalukIds = districtTalukIds +\",\" + $(this).val();\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t/*  $('#clonedDiv .talukAddr').each(function(){\r\n");
      out.write("\t\t districtTalukAddrs = districtTalukAddrs +\"##\" + $(this).val();\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t $('#clonedDiv .talukPhone').each(function(){\r\n");
      out.write("\t\t districtTalukPhones = districtTalukPhones +\",\" + $(this).val();\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t $('#clonedDiv .talukMobile').each(function(){\r\n");
      out.write("\t\t districtTalukMobiles = districtTalukMobiles +\",\" + $(this).val();\r\n");
      out.write("\t });\r\n");
      out.write("\t  */\r\n");
      out.write("\tif(validateAddDistrictForm()){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"addDistrict.do\",\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\t\t'districtName':$('#districtNameId').val(),\r\n");
      out.write("\t\t\t'talukNo':districtTalukIds.substring(1)\r\n");
      out.write("\t\t\t/* 'talukAddr':districtTalukAddrs.substring(2),\r\n");
      out.write("\t\t\t'talukPhone':districtTalukPhones.substring(1),\r\n");
      out.write("\t\t\t'talukMobile':districtTalukMobiles.substring(1) */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess:function(response){\r\n");
      out.write("\t\t\talert(response);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\twindow.location.reload();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#divSaveBtnId').click(function(){\r\n");
      out.write("\tvar districtTalukIds = \"\";\r\n");
      out.write("\t/* var districtTalukAddrs = \"\";\r\n");
      out.write("\tvar districtTalukPhones = \"\";\r\n");
      out.write("\tvar districtTalukMobiles = \"\"; */\r\n");
      out.write("\t $('#talukClonedDiv .talukNo').each(function(){\r\n");
      out.write("\t\t districtTalukIds = districtTalukIds +\",\" + $(this).val();\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t/*  $('#talukClonedDiv .talukAddr').each(function(){\r\n");
      out.write("\t\t districtTalukAddrs = districtTalukAddrs +\"##\" + $(this).val();\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t $('#talukClonedDiv .talukPhone').each(function(){\r\n");
      out.write("\t\t districtTalukPhones = districtTalukPhones +\",\" + $(this).val();\r\n");
      out.write("\t });\r\n");
      out.write("\t \r\n");
      out.write("\t $('#talukClonedDiv .talukMobile').each(function(){\r\n");
      out.write("\t\t districtTalukMobiles = districtTalukMobiles +\",\" + $(this).val();\r\n");
      out.write("\t }); */\r\n");
      out.write("\tif(validateAddTalukForm()){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"addTaluk.do\",\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\t\t'districtTalukId':$('#talukDistrictId option:selected').val(),\r\n");
      out.write("\t\t\t'talukName':districtTalukIds.substring(1)\r\n");
      out.write("\t\t\t/* 'talukAddr':districtTalukAddrs.substring(2),\r\n");
      out.write("\t\t\t'talukPhone':districtTalukPhones.substring(1),\r\n");
      out.write("\t\t\t'talukMobile':districtTalukMobiles.substring(1) */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess:function(response){\r\n");
      out.write("\t\t\talert(response);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\twindow.location.reload();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#editTalukBtn').click(function(){\r\n");
      out.write("\tif(validateEditForm()){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"editTaluk.do\",\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\t\t'districtTalukId':$('#editTalukId').val(),\r\n");
      out.write("\t\t\t'districtName':$('#editDistrictNameId').val(),\r\n");
      out.write("\t\t\t'talukName':$('#editTalukNoId').val()\r\n");
      out.write("\t\t\t/* 'talukAddr':$('#editTalukAddrId').val(),\r\n");
      out.write("\t\t\t'talukPhone':$('#editTalukPhoneId').val(),\r\n");
      out.write("\t\t\t'talukMobile':$('#editTalukMobileId').val() */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess:function(response){\r\n");
      out.write("\t\t\talert(response);\r\n");
      out.write("\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#deleteTaluk').click(function(){\r\n");
      out.write("\tvar talukList = \"\";\r\n");
      out.write("\tvar districtNameList = \"\";\r\n");
      out.write("\t$('#dataTables-example input:checkbox:checked').each(function(){\r\n");
      out.write("\t\tif($(this).closest('tr').find('td:nth-child(1)').find('input[type=\"checkbox\"]').attr('id')!=undefined){\r\n");
      out.write("\t\t  talukList = talukList +\",\"+$(this).closest('tr').find('td:nth-child(1)').find('input[type=\"checkbox\"]').attr('id').trim();\r\n");
      out.write("\t\t  districtNameList = districtNameList +\",\"+$(this).closest('tr').find('td:nth-child(3)').text().trim();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tif(confirm(\"Are you sure want to Delete these Taluk \"+districtNameList.substring(1)+\" ? \")){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"deleteTaluk.do\",\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\t\t'districtTalukId':talukList.substring(1)},\r\n");
      out.write("\t\tsuccess:function(response){\r\n");
      out.write("\t\t\talert(response);\r\n");
      out.write("\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class='table-bordered table table-striped display'\r\n");
      out.write("\tstyle='width: 100%; font-size: 28px;'>\r\n");
      out.write("<tr>\r\n");
      out.write("\t\t<td colspan='8'>\r\n");
      out.write("\t\t\t<!-- <a href=\"#\" style=\"padding: 10px;background-color: #78C948;color:white;\" id=\"addDistrict\">Add New District</a> -->\r\n");
      out.write("\t\t\t<a href=\"#\" style=\"padding: 10px;background-color: darkolivegreen;color:white;\" id=\"addTaluk\">Add New Taluk</a>\r\n");
      out.write("\t\t\t<a style=\"padding: 10px;background-color: #FEBA17;color:white;\" id=\"editTaluk\">Edit</a>\r\n");
      out.write("\t\t\t<a style=\"padding: 10px;background-color: #EE3B41;color:white;\" id=\"deleteTaluk\">Delete</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           <div id=\"content\" style=\"margin-left: 0px !important\">\r\n");
      out.write("<div id=\"successMessage\"></div>\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"panel panel-default\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-striped table-bordered table-hover\" id=\"dataTables-example\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                           <!--  <th style=\"color:black !important\"></th> -->\r\n");
      out.write("                                            <th style=\"color:black !important\"><input type=\"checkbox\" id=\"all\" style=\"width:15px;\"/></th>\r\n");
      out.write("                                            <th style=\"color:black !important\"><b> #</b></th>\r\n");
      out.write("                                            <th style=\"color:black !important\"><b>District Name</b></th>\r\n");
      out.write("                                            <th style=\"color:black !important\"><b>Taluk Name</b></th>\r\n");
      out.write("                                             <!-- <th style=\"color:black !important\"><b>Address</b></th>\r\n");
      out.write("                                              <th style=\"color:black !important\"><b>Phone</b></th>\r\n");
      out.write("                                               <th style=\"color:black !important\"><b>Mobile</b></th> -->\r\n");
      out.write("                                           \r\n");
      out.write("                                        \r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                   \r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                     ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                          \r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"addDialog\" style=\"display: none;\">\r\n");
      out.write("\r\n");
      out.write("<img class=\"imgClose\" src=\"library/img/Close_SMS.png\"\r\n");
      out.write("\t\t\tstyle=\"width: 40px; border-width: 0px; float: right; margin-top: -43px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t<h2 class=\"bg_heading\">Add New District</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<span><b>Enter District Name:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"districtNameId\" name=\"districtName\" /><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"clonedDiv\">\r\n");
      out.write("\t\t<div id=\"fileCloneId\" style=\"border: 1px solid lightgrey;padding:6px;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("<span><b>Enter Taluk Name:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"talukNoId_1\" class=\"talukNo\" style=\"margin-left: 5px;width:118px;\"/><img src=\"library/img/add.JPG\" width=\"25px\" height=\"25px\" class=\"addFileId\" title=\"Add New Taluk Details\"/><br /> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<!-- <span><b>Enter Address:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"talukAddrId_1\" class=\"talukAddr\" style=\"margin-left: 5px;width:220px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<span><b>Enter Phone:</b></span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"talukPhoneId_1\" class=\"talukPhone\" style=\"margin-left: 16px;width:222px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<span><b>Enter Mobile:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"talukMobileId_1\" class=\"talukMobile\" maxlength=\"10\"  style=\"margin-left: 14px;width:222px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<input type=\"button\" value=\"Save\" id=\"talukSaveBtnId\"/> <input type=\"button\" value=\"Close\"  class=\"closeBtn\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("<div id=\"addTalukDialog\" style=\"display: none;\">\r\n");
      out.write("\r\n");
      out.write("<img class=\"imgClose\" src=\"library/img/Close_SMS.png\"\r\n");
      out.write("\t\t\tstyle=\"width: 40px; border-width: 0px; float: right; margin-top: -43px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t<h2 class=\"bg_heading\">Add New Taluk</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<span><b>Select District Name:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("<select id=\"talukDistrictId\" name=\"talukDistrictName\">\r\n");
      out.write("<option value=\"\">---</option>\r\n");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</select><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"talukClonedDiv\">\r\n");
      out.write("\t\t<div id=\"talukFileCloneId\" style=\"border: 1px solid lightgrey;padding:6px;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("<span><b>Enter Taluk Name:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"divNoId_1\" class=\"talukNo\" style=\"margin-left: 5px;width:118px;\"/><img src=\"library/img/add.JPG\" width=\"25px\" height=\"25px\" class=\"addFileId\" title=\"Add New Taluk Details\"/><br /> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<!-- <span><b>Enter Address:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"divAddrId_1\" class=\"talukAddr\" style=\"margin-left: 5px;width:220px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<span><b>Enter Phone:</b></span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"divPhoneId_1\" class=\"talukPhone\" style=\"margin-left: 16px;width:222px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<span><b>Enter Mobile:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"divMobileId_1\" class=\"talukMobile\"  maxlength=\"10\" style=\"margin-left: 14px;width:222px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<input type=\"button\" value=\"Save\" id=\"divSaveBtnId\"/> <input type=\"button\" value=\"Close\"  class=\"closeBtn\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"editDialog\" style=\"display: none;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<img class=\"imgClose\" src=\"library/img/Close_SMS.png\"\r\n");
      out.write("\t\t\tstyle=\"width: 40px; border-width: 0px; float: right; margin-top: -43px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t<h2 class=\"bg_heading\">Edit Taluk</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"editTalukId\"/>\r\n");
      out.write("                 <span><b>District Name:</b></span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"editDistrictNameId\" name=\"editDistrictName\" readonly=\"readonly\"/><br/>\r\n");
      out.write("                <span><b>Enter Taluk Name:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"editTalukNoId\" name=\"editTalukNo\" style=\"margin-left: 5px;width:118px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- <span><b>Enter Address:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"editTalukAddrId\" name=\"editTalukAddr\" style=\"margin-left: 5px;width:227px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<span><b>Enter Phone:</b></span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"editTalukPhoneId\" name=\"editTalukPhone\" style=\"margin-left: 16px;width:228px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<span><b>Enter Mobile:</b></span><span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t<input placeholder=\"Ex: ABC\" type=\"text\" id=\"editTalukMobileId\" name=\"editTalukMobile\"  maxlength=\"10\" style=\"margin-left: 14px;width:228px;\"/><br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"Update\" id=\"editTalukBtn\"/> <input type=\"button\" value=\"Close\" class=\"closeBtn\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"assets/plugins/dataTables/jquery.dataTables.js\"></script>\r\n");
      out.write("    <script src=\"assets/plugins/dataTables/dataTables.bootstrap.js\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("         $(document).ready(function () {\r\n");
      out.write("             $('#dataTables-example').dataTable();\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("             var idCount=2;\r\n");
      out.write("        \t $('#clonedDiv').on('click','.addFileId',function(){\r\n");
      out.write("        \t\t  var cloned = $('#fileCloneId').clone();\r\n");
      out.write("        \t\t  cloned.find('img.deleteFileId').remove();\r\n");
      out.write("        \t\t  cloned.attr('id','fileCloneId_'+idCount);\r\n");
      out.write("        \t\t  cloned.find('.talukNo').attr('id','talukNoId_'+idCount);\r\n");
      out.write("        \t\t  \r\n");
      out.write("        \t\t /*  cloned.find('.talukAddr').attr('id','talukAddrId_'+idCount);\r\n");
      out.write("        \t\t  cloned.find('.talukPhone').attr('id','talukPhoneId_'+idCount);\r\n");
      out.write("        \t\t  cloned.find('.talukMobile').attr('id','talukMobileId_'+idCount); */\r\n");
      out.write("        \t\t  \r\n");
      out.write("          \t\t cloned.find('.addFileId').after('<img src=\"library/img/delete.JPG\" width=\"25px\" height=\"25px\" class=\"deleteFileId\" title=\"Remove Taluk Details\"/>');\r\n");
      out.write("        \t\t $('#clonedDiv').append(cloned);\r\n");
      out.write("        \t\t idCount++;\r\n");
      out.write("        \t\t \r\n");
      out.write("        \t  });\r\n");
      out.write("        \t $('#clonedDiv').on('click','.deleteFileId',function(){\r\n");
      out.write("        \t\t  $(this).parent('div').remove();  \r\n");
      out.write("        \t\t});\r\n");
      out.write("        \t  \r\n");
      out.write("        \t \r\n");
      out.write("        \t  var idDivCount=2;\r\n");
      out.write("         \t $('#talukClonedDiv').on('click','.addFileId',function(){\r\n");
      out.write("         \t\t  var cloned = $('#talukFileCloneId').clone();\r\n");
      out.write("         \t\t  cloned.find('img.deleteFileId').remove();\r\n");
      out.write("         \t\t  cloned.attr('id','fileCloneId_'+idCount);\r\n");
      out.write("         \t\t  cloned.find('.talukNo').attr('id','divNoId_'+idCount);\r\n");
      out.write("         \t\t  \r\n");
      out.write("         \t\t  /* cloned.find('.talukAddr').attr('id','divAddrId_'+idCount);\r\n");
      out.write("         \t\t  cloned.find('.talukPhone').attr('id','divPhoneId_'+idCount);\r\n");
      out.write("         \t\t  cloned.find('.talukMobile').attr('id','divMobileId_'+idCount); */\r\n");
      out.write("         \t\t  \r\n");
      out.write("           \t\t cloned.find('.addFileId').after('<img src=\"library/img/delete.JPG\" width=\"25px\" height=\"25px\" class=\"deleteFileId\" title=\"Remove Taluk Details\"/>');\r\n");
      out.write("         \t\t $('#talukClonedDiv').append(cloned);\r\n");
      out.write("         \t\tidDivCount++;\r\n");
      out.write("         \t\t \r\n");
      out.write("         \t  });\r\n");
      out.write("         \t $('#talukClonedDiv').on('click','.deleteFileId',function(){\r\n");
      out.write("         \t\t  $(this).parent('div').remove();  \r\n");
      out.write("         \t\t});\r\n");
      out.write("         \t  \r\n");
      out.write("        \t \r\n");
      out.write("        \t \r\n");
      out.write("        \t \r\n");
      out.write("        \t \r\n");
      out.write("        \t \r\n");
      out.write("        \t \r\n");
      out.write("             \r\n");
      out.write("         });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/JSP/Form/districtTalukManagement.jsp(457,37) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/JSP/Form/districtTalukManagement.jsp(457,37) '${list.districtTalukDtl}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list.districtTalukDtl}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/JSP/Form/districtTalukManagement.jsp(457,37) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("app");
    // /WEB-INF/views/JSP/Form/districtTalukManagement.jsp(457,37) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("count");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          \r\n");
          out.write("                                               <tr class=\"odd gradeX\">\r\n");
          out.write("          \t\t\t\t\t\t\t\t\r\n");
          out.write("          \t\t\t\t\t\t\t\r\n");
          out.write("                                            <td><input type=\"checkbox\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getTalukId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" style=\"width:15px;\"/></td>\r\n");
          out.write("                                            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                             <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getDistrictName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                             <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getTalukName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("                                             \r\n");
          out.write("                                            ");
          out.write("\r\n");
          out.write("                                           \r\n");
          out.write("                                           \r\n");
          out.write("                                        </tr>\t\r\n");
          out.write("          \r\n");
          out.write("          \t\t\t\t\t\t\t ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/JSP/Form/districtTalukManagement.jsp(536,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("var");
    // /WEB-INF/views/JSP/Form/districtTalukManagement.jsp(536,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/JSP/Form/districtTalukManagement.jsp(536,0) '${list.districtMap}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list.districtMap}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${var.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${var.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
