/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2019-02-17 17:18:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JSP.Form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class initialPayment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http//www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"library/assets/plugins/bootstrap/css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"library/assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"library/assets/css/theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"library/assets/css/MoneAdmin.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"library/assets/plugins/Font-Awesome/css/font-awesome.css\" />\r\n");
      out.write("<!--END GLOBAL STYLES -->\r\n");
      out.write("\r\n");
      out.write("<!-- PAGE LEVEL STYLES -->\r\n");
      out.write("<link href=\"library/assets/plugins/dataTables/dataTables.bootstrap.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write(" <script src=\"library/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#myTable td{\r\n");
      out.write("padding-left:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myTable td span{\r\n");
      out.write("margin-left:10px;\r\n");
      out.write("}\r\n");
      out.write(".error{\r\n");
      out.write("color:red;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("input[type=\"button\"] {\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    background-color: #2DAAE1;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    padding: 5px 5px 5px 5px;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#initialId tr:nth-child(even) {background: white;height:40px;}\r\n");
      out.write("#initialId tr:nth-child(odd) {background:#EDEDED ;height:40px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".tdPadding{\r\n");
      out.write("padding-left:305px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".ddDateClass\").datepicker({\r\n");
      out.write("\t\tdateFormat : 'dd-mm-yy',\r\n");
      out.write("\t\tchangeMonth : true,\r\n");
      out.write("\t\tchangeYear : true,\r\n");
      out.write("\t\tmaxDate : new Date(),\r\n");
      out.write("\t\tshowOn : \"button\",\r\n");
      out.write("\t\tbuttonImageOnly : true,\r\n");
      out.write("\t\tbuttonText : \"Select date\",\r\n");
      out.write("\t\tbuttonImage : \"library/img/datepicker.png\",\r\n");
      out.write("\t\tshowAnim : \"slideDown\",\r\n");
      out.write("\t});\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\tfunction validateForm(){\r\n");
      out.write("\t \r\n");
      out.write("\t    var numberReg =  /^[0-9]+$/;\r\n");
      out.write("\t    var dateReg =  /^\\d{2}-\\d{2}-\\d{4}$/;\r\n");
      out.write("\t    var appId  =\t$(\"#appId\");\r\n");
      out.write("\t    var paymentDDAmountId = $('#paymentDDAmountId');\r\n");
      out.write("\t    var paymentDDNoId = $('#paymentDDNoId');\r\n");
      out.write("\t    var paymentDDDateId = $('#paymentDDDateId');\r\n");
      out.write("\t    var paymentDDBankNameId = $('#paymentDDBankNameId');\r\n");
      out.write("\t    var flag = true;\r\n");
      out.write("\t\r\n");
      out.write("\t    var inputVal = new Array(appId, paymentDDAmountId,paymentDDNoId,paymentDDDateId,paymentDDBankNameId);\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t     $('.error').hide();\r\n");
      out.write("\t\tfor(var i=0;i<inputVal.length;i++){\r\n");
      out.write("\t        if(inputVal[i].val() == \"\"){\r\n");
      out.write("\t        \tinputVal[i].after('<span class=\"error\"> This field is required. </span>');\r\n");
      out.write("\t        \tinputVal[i].focus();\r\n");
      out.write("\t        \tflag = false;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        else if(inputVal[i].attr('id')=='paymentDDAmountId' && !numberReg.test(inputVal[i].val())){\r\n");
      out.write("\t        \tinputVal[i].after('<span class=\"error\"> Please enter DD Amount in Numeric</span>');\r\n");
      out.write("\t        \tinputVal[i].focus();\r\n");
      out.write("\t        \tflag = false;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        else if(inputVal[i].attr('id')=='paymentDDNoId' && !numberReg.test(inputVal[i].val())){\r\n");
      out.write("\t        \tinputVal[i].after('<span class=\"error\"> Please enter DD Number in Numeric</span>');\r\n");
      out.write("\t        \tinputVal[i].focus();\r\n");
      out.write("\t        \tflag = false;\r\n");
      out.write("\t        }\r\n");
      out.write("\t       /*  else if(inputVal[i].attr('id')=='paymentDDDateId' && !dateReg.test(inputVal[i].val())){\r\n");
      out.write("\t        \tinputVal[i].after('<span class=\"error\"> Please enter date in DD-MM-YYYY format </span>');\r\n");
      out.write("\t        \tinputVal[i].focus();\r\n");
      out.write("\t        \tflag = false;\r\n");
      out.write("\t        }  */\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\treturn flag;\r\n");
      out.write(" }\r\n");
      out.write("\t$('#submitPaymentId').click(function(){\r\n");
      out.write("\t\tif(validateForm())\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(confirm(\"Are you sure want to Submit ?\")){\r\n");
      out.write("\t\t\t$('#loading_image').show();\r\n");
      out.write("\t\t\tvar dataString = $('#formId').serialize();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\turl : \"saveDDPaymentDtls.do\",\r\n");
      out.write("\t\t\t\tdata : dataString,\r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" style=\"width: 1200px; font-size: 28px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td valign=\"middle\" style=\"height:155px;width: 100%;\"> \r\n");
      out.write("   <table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" align=\"center\"><img src=\"library/img/twad_logo.gif\" width=\"110px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"106px\" style=\"margin-left: 50px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"50%\" align=\"center\"><img src=\"library/img/middleImage.png\" width=\"560px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"67px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td  width=\"25%\" align=\"center\"><img src=\"library/img/pic6_2.jpg\" width=\"130px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"130px\" style=\"margin-right: 50px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("  </td></tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("\t\t\t<td height=\"25px\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"padding: 0px; width: 100%;\">\r\n");
      out.write("                <div style=\"background-image: url(library/img/border_bg.gif); height: 7px; background-repeat: repeat-x;\">\r\n");
      out.write("                    &nbsp;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<img src=\"library/img/loader.gif\" style=\"display: none;\" id=\"loading_image\">\r\n");
      out.write("\t\r\n");
      out.write("<table id=\"statusHeader\" align=\"center\" class=\"table-bordered table table-striped display\" style=\"width: 970px;\">\r\n");
      out.write("\r\n");
      out.write("\t<tbody><tr>\r\n");
      out.write("\t\t<td style=\"text-align: center; background-color: #FCFCF4; font-size: 25px; height: 10px; color: #800000; font-weight: bold;\">Payment</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("</tbody></table>\r\n");
      out.write("\t<form id=\"formId\" style=\"width:970px;margin-left: 195px;\">\r\n");
      out.write("\t<table id=\"initialId\" width=\"100%\" align=\"center\" style=\"margin-left: 0px;\">\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<tr><td class=\"tdPadding\" width=\"50%\"><b>Enter Application Ref:</b><span style=\"color:red;\">*</span></td><td><input type=\"text\" placeholder =\"Enter Application Ref\" id=\"appId\" name=\"appId\" value=\"\"/></td></tr>\r\n");
      out.write(" <!-- <tr><td class=\"tdPadding\" width=\"50%\"><b>GST Amount(GST @ 18 %):</b><span style=\"color:red;\">*</span></td><td><input type=\"text\" readonly placeholder =\"Auto populate\"  id=\"paymentGSTAmountId\" name=\"paymentGSTAmount\" style=\"background-color: lightgrey;\"/></td></tr> -->\r\n");
      out.write(" <tr><td class=\"tdPadding\" width=\"50%\"><b>DD Amount:</b><span style=\"color:red;\">*</span></td><td><input type=\"text\" placeholder =\"DD Amount\" title=\"Please enter DD Amount\" id=\"paymentDDAmountId\" name=\"paymentAmount\" /></td></tr>\r\n");
      out.write(" <tr><td class=\"tdPadding\" width=\"50%\"><b>DD NO:</b><span style=\"color:red;\">*</span></td><td><input type=\"text\"  placeholder =\"123456\" title=\"Please Enter DD No\" id=\"paymentDDNoId\" name=\"ddNo\"/></td></tr>\r\n");
      out.write(" <tr><td class=\"tdPadding\" width=\"50%\"><b>DD Date:</b><span style=\"color:red;\">*</span></td><td><input type=\"text\"  placeholder =\"DD-MM-YYYY\" readonly title=\"Please Enter DD Date\" class=\"ddDateClass\" id=\"paymentDDDateId\" name=\"ddDate\" /></td></tr>\r\n");
      out.write(" <tr><td class=\"tdPadding\" width=\"50%\"><b>Bank Name:</b><span style=\"color:red;\">*</span></td><td><input type=\"text\"  placeholder =\"Ex Indian Bank\" title=\"Please Enter Bank Name\" id=\"paymentDDBankNameId\" name=\"ddBankName\"/></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td colspan=\"2\" align=\"center\" style=\"height: 50px;\">\r\n");
      out.write("<input type=\"button\" id=\"submitPaymentId\"   value=\"Submit\"/> <a href=\"/TwadWeb/index.do\">Back to Home Page </a>\r\n");
      out.write("\r\n");
      out.write("</td></tr></tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\t</body>\r\n");
      out.write("\t\t\t</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
