/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2019-02-16 18:36:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JSP.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class eeheaderMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#HDropdown-orange-classic {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 0%) repeat\r\n");
      out.write("\t\tscroll 0 0 rgba(0, 0, 0, 0);\r\n");
      out.write("\t/* Chrome,Safari4+ */\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\tbackground: linear-gradient(from top to bottom, #FFFFFF 0%, #1589FF 0%);\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* For Safari 5.1 to 6.0 */\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* Chrome10+,Safari5.1+ */\r\n");
      out.write("\tbackground: -moz-linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* FF3.6+ */\r\n");
      out.write("\tbackground: -ms-linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* IE10+ */\r\n");
      out.write("\tbackground: -o-linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* Opera 11.10+ */\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder: solid 1px #1589FF;\r\n");
      out.write("\tborder-width: 1px 1px 1px 0;\r\n");
      out.write("\tbackground: -o-linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 0%) repeat\r\n");
      out.write("\t\tscroll 0 0 rgba(0, 0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\tline-height: 26px;\r\n");
      out.write("\tpadding: 0 25px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tborder-left: solid 1px #E6D9D9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li a:hover {\r\n");
      out.write("\t/* \tcolor: #FFFFFF; */\r\n");
      out.write("\t/* \tbackground: #FFFFFF; */\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tline-height: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 23px;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tborder: solid 1px #E6D9D9;\r\n");
      out.write("\tborder-width: 0px 1px 1px 1px;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li:hover ul {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\t/* \tbackground-color:#FFFFFF; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li a:hover {\r\n");
      out.write("\t/* \tcolor: #FFFFFF; */\r\n");
      out.write("\tbackground: #E05400;\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 3%, #E05400 30%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul li {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tborder-bottom: solid 1px #dbdcd9;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tbackground: url(library/img/menubg.jpg) repeat-x top no-repeat 3px 12px;\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 10%) repeat\r\n");
      out.write("\t\tscroll 0 0 rgba(0, 0, 0, 0);\r\n");
      out.write("\t/* Chrome,Safari4+ */\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 1%, #1589FF 10%);\r\n");
      out.write("\tbackground: linear-gradient(from top to bottom, #FFFFFF 0%, #1589FF 50%);\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\t/* For Safari 5.1 to 6.0 */\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\t/* Chrome10+,Safari5.1+ */\r\n");
      out.write("\tbackground: -moz-linear-gradient(top, #FFFFFF 1%, #1589FF 10%);\r\n");
      out.write("\t/* FF3.6+ */\r\n");
      out.write("\tbackground: -ms-linear-gradient(top, #FFFFFF 1%, #1589FF 50%); */\r\n");
      out.write("\t/* IE10+ */\r\n");
      out.write("\t/* \tbackground: -o-linear-gradient(top, #FFFFFF 1%, #1589FF 50%); */\r\n");
      out.write("\t/* Opera 11.10+ */\r\n");
      out.write("\t/* \tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 50%); */\r\n");
      out.write("\tpadding: 0 0 0 1px;\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\t/* For Safari 5.1 to 6.0 */\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\t/* Chrome10+,Safari5.1+ */\r\n");
      out.write("\tbackground: -moz-linear-gradient(top, #FFFFFF 1%, #1589FF 10%);\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul li:HOVER {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tborder-bottom: solid 1px #dbdcd9;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\t/* \tbackground: #85807F; */\r\n");
      out.write("\tbackground: #E05400;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tpadding: 0 0 0 1px;\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 3%, #E05400 30%);\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul li:last-child {\r\n");
      out.write("\tborder-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul a {\r\n");
      out.write("\tborder-width: 0px;\r\n");
      out.write("\t/* \tcolor: #FFFFFF; */\r\n");
      out.write("\tpadding: 0 1px 0 10px;\r\n");
      out.write("\tbackground-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li:hover ul li a {\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul li a:hover {\r\n");
      out.write("\t/* \tcolor: #FFFFFF; */\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<ul id=\"HDropdown-orange-classic\">\r\n");
      out.write("\t\t<!-- <li><a href=\"home.do\"><img src='library/img/home.png'/></a> -->\r\n");
      out.write("\t\t<li><a href=\"eeDashboard.do\" id='menu1' > Dashboard</a> <!-- \t\t\t<ul> -->\r\n");
      out.write("\t\t\t<!--  \t\t\t<li><a href=\"studentList.do\">Student Details</a></li> --> <!-- \t\t\t\t<li><a href=\"studentRegistration.do\">Student Registration</a></li> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t</ul> --></li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li><a href=\"eeBeforeInsp.do\" id='menu2'>Before Inspection </a> <!-- \t\t\t<ul> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t<li><a href=\"viewResult.do\">View Result</a></li> --> <!-- \t\t\t</ul> -->\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t<!-- \t<li><a href=\"eeAfterInsp.do\" id='menu2'>After Inspection & Payment Estimation</a> \t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"viewResult.do\">View Result</a></li> \t\t\t</ul>\r\n");
      out.write("\t\t</li> -->\r\n");
      out.write("\t\t<li><a href=\"eeAfterInsp.do\" id='menu2'>Inspection & Document</a> <!-- \t\t\t<ul> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t<li><a href=\"viewResult.do\">View Result</a></li> --> <!-- \t\t\t</ul> -->\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li><a href=\"eeEstimate.do\" id='menu2'>Estimate & Document</a> <!-- \t\t\t<ul> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t<li><a href=\"viewResult.do\">View Result</a></li> --> <!-- \t\t\t</ul> -->\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li><a href=\"eeMOU.do\" id='menu2'>MOU & Document</a> <!-- \t\t\t<ul> -->\r\n");
      out.write("\t\t\t<!-- \t\t\t\t<li><a href=\"viewResult.do\">View Result</a></li> --> <!-- \t\t\t</ul> -->\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- <li><a href=\"eeProsFeePendingApp.do\" id='menu2'> ProcessingFee Payment Pending  </a> \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"viewResult.do\">View Result</a></li> \t\t\t</ul>\r\n");
      out.write("\t\t</li>  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--  <li><a href=\"eeApproved.do\" id='menu2'> Approved  Application</a> \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"viewResult.do\">View Result</a></li> \t\t\t</ul>\r\n");
      out.write("\t\t</li>  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <li><a href=\"eeApproved.do\" id='menu2'> Approved  Application</a> \t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- \t<li><a href=\"viewResult.do\">View Result</a></li> \t\t\t</ul> -->\r\n");
      out.write("\t\t</li> \r\n");
      out.write("\t\t<li><a href=\"eeConPayPendingApp.do\" id='menu2'>  Payment Pending Application </a> \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"viewResult.do\">View Result</a></li> \t\t\t</ul> -->\r\n");
      out.write("\t\t</li> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  <li><a href=\"eeConPaidApp.do\" id='menu2'>Payment Paid Application </a> \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"viewResult.do\">View Result</a></li> \t\t\t</ul> -->\r\n");
      out.write("\t\t</li> \r\n");
      out.write("\t\t<li><a href=\"eeViewAll.do\" id='menu2'>View All Application </a> \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"viewResult.do\">View Result</a></li> \t\t\t</ul> -->\r\n");
      out.write("\t\t</li>  \r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("<br>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
