/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2019-02-16 18:31:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JSP.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class headerTop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#HDropdown-orange-classic {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 0%) repeat\r\n");
      out.write("\t\tscroll 0 0 rgba(0, 0, 0, 0);\r\n");
      out.write("\t/* Chrome,Safari4+ */\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\tbackground: linear-gradient(from top to bottom, #FFFFFF 0%, #1589FF 0%);\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* For Safari 5.1 to 6.0 */\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* Chrome10+,Safari5.1+ */\r\n");
      out.write("\tbackground: -moz-linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* FF3.6+ */\r\n");
      out.write("\tbackground: -ms-linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* IE10+ */\r\n");
      out.write("\tbackground: -o-linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\t/* Opera 11.10+ */\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder: solid 1px #1589FF;\r\n");
      out.write("\tborder-width: 1px 1px 1px 0;\r\n");
      out.write("\tbackground: -o-linear-gradient(top, #FFFFFF 1%, #1589FF 0%);\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 0%) repeat\r\n");
      out.write("\t\tscroll 0 0 rgba(0, 0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\tline-height: 26px;\r\n");
      out.write("\tpadding: 0 25px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tborder-left: solid 1px #E6D9D9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li a:hover {\r\n");
      out.write("\t/* \tcolor: #FFFFFF; */\r\n");
      out.write("\t/* \tbackground: #FFFFFF; */\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tline-height: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 23px;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tborder: solid 1px #E6D9D9;\r\n");
      out.write("\tborder-width: 0px 1px 1px 1px;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li:hover ul {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\t/* \tbackground-color:#FFFFFF; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li a:hover {\r\n");
      out.write("\t/* \tcolor: #FFFFFF; */\r\n");
      out.write("\tbackground: #E05400;\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 3%, #E05400 30%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul li {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tborder-bottom: solid 1px #dbdcd9;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tbackground: url(library/img/menubg.jpg) repeat-x top no-repeat 3px 12px;\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 10%) repeat\r\n");
      out.write("\t\tscroll 0 0 rgba(0, 0, 0, 0);\r\n");
      out.write("\t/* Chrome,Safari4+ */\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 1%, #1589FF 10%);\r\n");
      out.write("\tbackground: linear-gradient(from top to bottom, #FFFFFF 0%, #1589FF 50%);\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\t/* For Safari 5.1 to 6.0 */\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\t/* Chrome10+,Safari5.1+ */\r\n");
      out.write("\tbackground: -moz-linear-gradient(top, #FFFFFF 1%, #1589FF 10%);\r\n");
      out.write("\t/* FF3.6+ */\r\n");
      out.write("\tbackground: -ms-linear-gradient(top, #FFFFFF 1%, #1589FF 50%); */\r\n");
      out.write("\t/* IE10+ */\r\n");
      out.write("\t/* \tbackground: -o-linear-gradient(top, #FFFFFF 1%, #1589FF 50%); */\r\n");
      out.write("\t/* Opera 11.10+ */\r\n");
      out.write("\t/* \tbackground: linear-gradient(to bottom, #FFFFFF 1%, #1589FF 50%); */\r\n");
      out.write("\tpadding: 0 0 0 1px;\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\t/* For Safari 5.1 to 6.0 */\r\n");
      out.write("\tbackground: linear-gradient(top, #FFFFFF 1%, #1589FF 50%);\r\n");
      out.write("\t/* Chrome10+,Safari5.1+ */\r\n");
      out.write("\tbackground: -moz-linear-gradient(top, #FFFFFF 1%, #1589FF 10%);\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul li:HOVER {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tborder-bottom: solid 1px #dbdcd9;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\t/* \tbackground: #85807F; */\r\n");
      out.write("\tbackground: #E05400;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tpadding: 0 0 0 1px;\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 3%, #E05400 30%);\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul li:last-child {\r\n");
      out.write("\tborder-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul a {\r\n");
      out.write("\tborder-width: 0px;\r\n");
      out.write("\t/* \tcolor: #FFFFFF; */\r\n");
      out.write("\tpadding: 0 1px 0 10px;\r\n");
      out.write("\tbackground-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li:hover ul li a {\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#HDropdown-orange-classic li ul li a:hover {\r\n");
      out.write("\t/* \tcolor: #FFFFFF; */\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<table class='table tabel-striped bootstrap-datatable '\t\r\n");
      out.write("\t\tstyle='border-bottom: 1px solid #1589FF;'>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 10%;\"><a href='home.do'><img\r\n");
      out.write("\t\t\t\t\ttitle='EC Home' src='library/img/EC_logo.jpg' width=\"75px\" height=\"75px\"></a></td>\r\n");
      out.write("\t\t\t<td\r\n");
      out.write("\t\t\t\tstyle=\"text-align: center; font-family: alice; width: 60%; color: #1589FF; font-size: 34px;font-weight:bold;\">\r\n");
      out.write("\t\t\t\t<font color=\"blue\"> New Water Connections</font> </td>\r\n");
      out.write("\t\t\t<td\r\n");
      out.write("\t\t\t\tstyle='text-align: right; width: 20%; color: #1589FF; text-shadow: 1px 7px 10px #a6a1a1; font-size: 14px;'>\r\n");
      out.write("\t\t\t\tHi! ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write(" <a href='signOut.do'\r\n");
      out.write("\t\t\t\ttitle='Sign Out'><img src='library/img/logout.png'> Sign Out </a><br/><br/>\r\n");
      out.write("\t\t\t\t<a href=\"changePasswordPage.do\">Change Password </a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<!-- \t\t\t<td style=\"text-align: right;font-size: 10px;\"><a href=\"?lang=en\">English</a> | <a href=\"?lang=de\">Language2</a></td> -->\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/JSP/common/headerTop.jsp(157,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.LoginName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
