/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2019-02-16 18:24:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JSP.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"library/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"library/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script src=\"library/js/jquery-ui-1.8.21.custom.min.js\"></script>\r\n");
      out.write("<script src='library/js/jquery.dataTables.min.js'></script>\r\n");
      out.write("<script src='library/js/chosen.jquery.js'></script>\r\n");
      out.write("<script src='library/js/jquery.validate.js'></script>\r\n");
      out.write("<script src='library/js/dataTables.fixedColumns.js'></script>\r\n");
      out.write("<script src='library/js/jquery-ui-timepicker-addon.js'></script>\r\n");
      out.write("<script src='JS/common.js'></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"library/css/jquery-ui-1.8.21.custom.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin: 0px; padding: 0px\" >\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<style>\r\n");
      out.write("#mydiv {\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\t/* height: 350px; */\r\n");
      out.write("\tmargin-left: -600px;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div[role=\"dialog\"] {\r\n");
      out.write("\tborder-radius: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginDialog {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\tpadding: 0px !important;\r\n");
      out.write("\toverflow: hidden !important;\r\n");
      out.write("}\r\n");
      out.write("/*\r\n");
      out.write(".open{\r\n");
      out.write("display:block;\r\n");
      out.write("} */\r\n");
      out.write("/* \r\n");
      out.write(".dropdown, .dropup {\r\n");
      out.write("    position: relative;\r\n");
      out.write("} */\r\n");
      out.write("input[type=\"button\"] {\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tbackground-color: #2DAAE1;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tpadding: 5px 5px 5px 5px;\r\n");
      out.write("\tmargin-left: 150px;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-dialog>.ui-widget-header {\r\n");
      out.write("\tbackground: blue;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-dialog {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-inline {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-family: Lato;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-slide {\r\n");
      out.write("\t/*  display: inline-block; */\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-family: Lato;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\t/*  margin-left: 10px; */\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 100%;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tz-index: 1000;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmin-width: 160px;\r\n");
      out.write("\tpadding: 5px 0;\r\n");
      out.write("\tmargin: 2px 0 0;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\t-webkit-background-clip: padding-box;\r\n");
      out.write("\tbackground-clip: padding-box;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tborder: 1px solid rgba(0, 0, 0, .15);\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\t-webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, .175);\r\n");
      out.write("\tbox-shadow: 0 6px 12px rgba(0, 0, 0, .175);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu>li>a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 3px 20px;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tline-height: 1.42857143;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ftrmenu {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".caret {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 0;\r\n");
      out.write("\theight: 0;\r\n");
      out.write("\tmargin-left: 2px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tborder-top: 4px dashed;\r\n");
      out.write("\tborder-top: 4px solid\\9;\r\n");
      out.write("\tborder-right: 4px solid transparent;\r\n");
      out.write("\tborder-left: 4px solid transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg_heading {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tfont-family: Lato;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tbackground-color: #2DAAE1;\r\n");
      out.write("\tborder-radius: 15px 0px 0px 0px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"],input[type=\"password\"] {\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("\tmargin-left: 60px;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* \r\n");
      out.write(".jssora05l {\r\n");
      out.write("    background-position: -10px -40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jssora05l, .jssora05r, .jssora05ldn, .jssora05rdn {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    display: block;\r\n");
      out.write("    background: url(New_library/img/a17.png) no-repeat;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu > li > a {\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu>li>a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 3px 20px;\r\n");
      out.write("    clear: both;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    line-height: 1.42857143;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write(" */\r\n");
      out.write(".dropdown-menu .divider {\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tmargin: 9px 0;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbackground-color: #e5e5e5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#map {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("/* Optional: Makes the sample page fill the window. */\r\n");
      out.write("html,body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tlocalStorage.setItem('isDetailButtonClicked', null);\r\n");
      out.write("\t\t\tlocalStorage.setItem('isStatusButtonClicked', null);\r\n");
      out.write("\t\t\tlocalStorage.setItem('registeredData', null);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<table id=\"mydiv\">\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td valign=\"middle\" colspan=\"2\" style=\"height: 130px; width: 100%;\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" align=\"center\"><img src=\"library/img/twad_logo.gif\" width=\"110px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"106px\" style=\"margin-left: 50px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"50%\" align=\"center\"><img src=\"library/img/middleImage.png\" width=\"560px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"67px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td  width=\"25%\" align=\"center\"><img src=\"library/img/pic6_2.jpg\" width=\"130px\"\r\n");
      out.write("\t\t\t\t\t\t\t\theight=\"130px\" style=\"margin-right: 50px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td colspan=\"2\" height=\"10px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"padding: 0px; width: 100%;\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-image: url(library/img/border_bg.jpg); height: 10px; background-repeat: repeat-x;\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("<td valign=\"top\" align=\"center\" style=\"width: 100%;\">\r\n");
      out.write("    <div style=\"width: 460px; margin-top: 80px;height: 350px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 0px !important; list-style-type: none; padding: 0px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown-slide\" id=\"companyLogin\" style=\"background-color: #FED367; width: 100%; border-bottom: 2px solid #fff; border-right: none !important;\"><a href=\"/TwadWeb/formRegister.do\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<table style=\"width: 100%;\" id=\"companyRegistration\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 20%;\"><img src=\"library/img/new.png\" style=\"padding-left: 10px; padding-right: 10px; height: 50px; width: 50px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 5%;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 70%;\" class=\"menu_multi_line\"><span style=\"font-size: 16px; color: Black;\"> <span id=\"Label2\">New water connection Registration\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</span></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 5%;\" align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown-slide\" style=\"background-color: #FED367; width: 100%; border-bottom: 2px solid #fff; border-right: none !important;\"><a href=\"/TwadWeb/adminLogin.do\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<table style=\"width: 100%;\" id=\"departmentLogin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 20%;\"><img src=\"library/img/login.jpg\" style=\"padding-left: 10px; padding-right: 10px; height: 50px; width: 50px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 5%;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 70%;\" class=\"menu_multi_line\"><span style=\"font-size: 16px; color: Black;\"> <span id=\"Label2\">TWAD Login</span></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 5%;\" align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown-slide\" style=\"background-color: #FED367; width: 100%; border-bottom: 2px solid #fff; border-right: none !important;\"><a href=\"/TwadWeb/checkApplicationStatus.do?appId=\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<table style=\"width: 100%;\" id=\"applicationStatus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 20%;\"><img src=\"library/img/application.png\" style=\"padding-left: 10px; padding-right: 10px; height: 50px; width: 50px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 5%;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 70%;\" class=\"menu_multi_line\"><span style=\"font-size: 16px; color: Black;\"> <span id=\"Label2\">Application Status</span></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 5%;\" align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown-slide\" style=\"background-color: #FED367; width: 100%; border-bottom: 2px solid #fff; border-right: none !important;\"><a href=\"/TwadWeb/initialPayment.do\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<table style=\"width: 100%;\" id=\"initialPayment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 20%;\"><img src=\"library/img/RS.jpg\" style=\"padding-left: 10px; padding-right: 10px; height: 50px; width: 50px !important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 5%;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 70%;\" class=\"menu_multi_line\"><span style=\"font-size: 16px; color: Black;\"> <span id=\"Label2\">Payment</span></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style=\"width: 5%;\" align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<!--   <li class=\"dropdown-slide\" style=\"background-color: #FED367; width: 100%; border-bottom: 2px solid #fff;\r\n");
      out.write("                                border-right: none !important;\"><a href=\"/Water/initialPayment.do\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                    <table style=\"width: 100%;\" id=\"initialPayment\">\r\n");
      out.write("                                        <tbody><tr>\r\n");
      out.write("                                            <td style=\"width: 20%;\">\r\n");
      out.write("                                                <img src=\"library/img/icon_home5.png\" style=\"padding-left: 10px; padding-right: 10px;\r\n");
      out.write("                                                    height: 50px;\">\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td style=\"width: 5%;\">\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td style=\"width: 70%;\" class=\"menu_multi_line\">\r\n");
      out.write("                                                <span style=\"font-size: 16px; color: Black;\">\r\n");
      out.write("                                                    <span id=\"Label2\">Withdraw Application</span></span>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td style=\"width: 5%;\" align=\"center\">\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </tbody></table>\r\n");
      out.write("                                </a>\r\n");
      out.write("                              \r\n");
      out.write("                                \r\n");
      out.write("                                </li>  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\"><hr /></td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"validate.do\" id=\"formId\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"loginDialog\" id=\"adminLoginDialog\">\r\n");
      out.write("\t\t\t<img class=\"imgClose\" src=\"library/img/Close_SMS.png\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 40px; border-width: 0px; float: right; margin-top: -6px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t\t<h2 class=\"bg_heading\">Admin Login</h2>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"userName\" placeholder=\"Enter User Name\" />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"loginPassword\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Enter Password\" />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" id=\"adminLoginId\" Value=\"Login\" />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p style=\"padding-left: 30px;\">\r\n");
      out.write("\t\t\t\tForgot Password? <a href=\"#\">Click here</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"loginDialog\" id=\"cELoginDialog\">\r\n");
      out.write("\t\t<img class=\"imgClose\" src=\"library/img/Close_SMS.png\"\r\n");
      out.write("\t\t\tstyle=\"width: 40px; border-width: 0px; float: right; margin-top: -6px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t<h2 class=\"bg_heading\">CE Login</h2>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"userName\" placeholder=\"Enter User Name\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"password\" placeholder=\"Enter Password\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"cELoginId\" Value=\"Login\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"padding-left: 30px;\">\r\n");
      out.write("\t\t\tForgot Password? <a href=\"#\">Click here</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"loginDialog\" id=\"eELoginDialog\">\r\n");
      out.write("\t\t<img class=\"imgClose\" src=\"library/img/Close_SMS.png\"\r\n");
      out.write("\t\t\tstyle=\"width: 40px; border-width: 0px; float: right; margin-top: -6px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t<h2 class=\"bg_heading\">EE Login</h2>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"userName\" placeholder=\"Enter User Name\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"password\" placeholder=\"Enter Password\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"eELoginId\" Value=\"Login\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"padding-left: 30px;\">\r\n");
      out.write("\t\t\tForgot Password? <a href=\"#\">Click here</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"loginDialog\" id=\"companyLoginDialog\">\r\n");
      out.write("\t\t<img class=\"imgClose\" src=\"library/img/Close_SMS.png\"\r\n");
      out.write("\t\t\tstyle=\"width: 40px; border-width: 0px; float: right; margin-top: -6px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t<h2 class=\"bg_heading\">Company Login</h2>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"userName\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Enter Application Reference\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"password\" placeholder=\"Enter Password\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"companyLoginId\" Value=\"Login\" />\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"padding-left: 30px;\">\r\n");
      out.write("\t\t\tForgot Password? <a href=\"#\">Click here</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"padding-left: 30px;\">\r\n");
      out.write("\t\t\tNew User? <a href=\"/TwadWeb/formRegister.do\">Click here</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
