/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2019-02-16 18:36:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JSP.Application;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class eeafterInsp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"library/assets/plugins/bootstrap/css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"library/assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"library/assets/css/theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"library/assets/css/MoneAdmin.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"library/assets/plugins/Font-Awesome/css/font-awesome.css\" />\r\n");
      out.write("<!--END GLOBAL STYLES -->\r\n");
      out.write("\r\n");
      out.write("<!-- PAGE LEVEL STYLES -->\r\n");
      out.write("<link href=\"library/assets/plugins/dataTables/dataTables.bootstrap.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write("input[type=text],input[type=password] {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\tpadding: 12px 20px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for all buttons */\r\n");
      out.write("button {\r\n");
      out.write("\tbackground-color: #0BB09F;\r\n");
      out.write("\t/* color: white;\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 15%; */\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tpadding: 10px 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Extra styles for the cancel button */\r\n");
      out.write(".cancelbtn {\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tpadding: 10px 18px;\r\n");
      out.write("\tbackground-color: #f44336;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tright: 50%;\r\n");
      out.write("}\r\n");
      out.write(".uploadbtn {\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tpadding: 10px 18px;\r\n");
      out.write("\tbackground-color: #DAB304;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tright: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Center the image and position the close button */\r\n");
      out.write(".imgcontainer {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 24px 0 12px 0;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgcontainer1 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 24px 0 12px 0;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.avatar {\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\tpadding: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.psw {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tpadding-top: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write(".modal {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\theight: 68%;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\twidth: 469px !important;\r\n");
      out.write("}\r\n");
      out.write(".modalr {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\theight: 38%;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\twidth: 469px !important;\r\n");
      out.write("}\r\n");
      out.write(".modalr td{\r\n");
      out.write("padding-top:100px;\r\n");
      out.write("padding-left:100px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".modal td{\r\n");
      out.write("padding-top:15px;\r\n");
      out.write("padding-left:10px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("select,input[type=\"text\"]{\r\n");
      out.write("width:150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal Content/Box */\r\n");
      out.write(".modal-content {\r\n");
      out.write("\tbackground-color: #fefefe;\r\n");
      out.write("\tmargin: 5% auto 15% auto;\r\n");
      out.write("\t/* 5% from the top, 15% from the bottom and centered */\r\n");
      out.write("\tborder: 0px solid #888;\r\n");
      out.write("\twidth: 80%; /* Could be more or less, depending on screen size */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modalr-content {\r\n");
      out.write("\tbackground-color: #fefefe;\r\n");
      out.write("\tmargin: 100% auto 100% auto;\r\n");
      out.write("\t/* 5% from the top, 15% from the bottom and centered */\r\n");
      out.write("\tborder: 0px solid #888;\r\n");
      out.write("\twidth: 80%; /* Could be more or less, depending on screen size */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* The Close Button (x) */\r\n");
      out.write(".popupclose {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 10px;\r\n");
      out.write("\ttop: 3px !important;\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tfont-size: 35px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popupclose:hover,.popupclose:focus {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add Zoom Animation */\r\n");
      out.write(".animate {\r\n");
      out.write("\t-webkit-animation: animatezoom 0.6s;\r\n");
      out.write("\tanimation: animatezoom 0.6s\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("-webkit-keyframes animatezoom {\r\n");
      out.write("\tfrom {-webkit-transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\t-webkit-transform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes animatezoom {\r\n");
      out.write("\tfrom {transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\ttransform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change styles for span and cancel button on extra small screens */\r\n");
      out.write("@media screen and (max-width: 300px) {\r\n");
      out.write("\tspan.psw {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.cancelbtn {\r\n");
      out.write("\t\twidth: 30%;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menu3 {\r\n");
      out.write("\tbackground: #E05400;\r\n");
      out.write("\tbackground: -webkit-linear-gradient(top, #FFFFFF 3%, #E05400 30%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"search\"] {\r\n");
      out.write("\theight: 30px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"] {\r\n");
      out.write("\theight: 25px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#successMessage {\r\n");
      out.write("\tmargin-left: 450px;\r\n");
      out.write("\tz-index: 20000;\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tcolor: green;\r\n");
      out.write("}\r\n");
      out.write(".row-fluid,.span12{\r\n");
      out.write("width:100% !important;\r\n");
      out.write("}\r\n");
      out.write("/* div[role=\"dialog\"]{\r\n");
      out.write("border-radius:15px; \r\n");
      out.write("}\r\n");
      out.write(".loginDialog{\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("\twidth:400px;\r\n");
      out.write("\theight:200px;\r\n");
      out.write("\tpadding:0px !important;\r\n");
      out.write("\toverflow: hidden !important;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write(" div[role=\"dialog\"]{\r\n");
      out.write("/* border-radius:15px;  */\r\n");
      out.write("left:410px !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- <script src='JS/complaints/searchComplaints.js'></script> -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("localStorage.setItem('isFileUploaded', false);\r\n");
      out.write("\tfunction getPaymentDetails(id) {\r\n");
      out.write("\t\t$('#id01').css({\r\n");
      out.write("\t\t\t'display' : 'block'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#appId').val(id);\r\n");
      out.write("\t\t$('#estCostAppId').val(id);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction gst() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(\"gst\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction Widthdraw(id) {\r\n");
      out.write("\t\t$('#id01').css({\r\n");
      out.write("\t\t\t'display' : 'block'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#appId').val(id);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : \"eeWidthdraw.do\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t'appRef' : appRef\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\twindow.location.reload();\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction eeReject(appRef){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tappRef = $('#rejectAppId').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar txtremarks = document.getElementById('txtremarks').value;\r\n");
      out.write("\t\tif (txtremarks == null || txtremarks == '') {\r\n");
      out.write("\t\t\talert(\"Please enter the  remarks !\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(confirm(\"Are you sure want to Reject?\")){\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : \"eeRejcted.do\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t'appRef' : appRef,'remarks':txtremarks\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t//\t$('#successMessage').text(response);\r\n");
      out.write("\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\twindow.location.reload();\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction gst(estimationcost){\r\n");
      out.write("\t\tvar estAmt = document.getElementById('txtestpayment').value;\r\n");
      out.write("\t\tvar gst=(estAmt*18)/100;\r\n");
      out.write("\t\tvar total=estAmt+gst;\r\n");
      out.write("\t\tvar g1=parseInt(gst);\r\n");
      out.write("\t\tvar t1=parseInt(estAmt);\r\n");
      out.write("\t\tvar total=g1+t1;\r\n");
      out.write("\t\t$(\"#gst\").val(g1);\r\n");
      out.write("\t\t$(\"#totalAmount\").val(total);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction SendEstimationCost(appRef) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tappRef = $('#estCostAppId').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar isnearest = document.getElementById(\"isnearest\").options[document.getElementById(\"isnearest\").selectedIndex].value;\r\n");
      out.write("\t\tvar isnewpipeline = document.getElementById(\"isnewpipeline\").options[document.getElementById(\"isnewpipeline\").selectedIndex].value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t var estimationCost = document.getElementById('txtestpayment').value;\r\n");
      out.write("\t\t var tentaiveDate = document.getElementById('tentaiveDate').value;\r\n");
      out.write("\t\t var gst = document.getElementById('gst').value;\r\n");
      out.write("\t\t var totalAmount = document.getElementById('totalAmount').value;\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t var isproposal=\"\";\r\n");
      out.write("\t\t if (isnearest == '3') {\r\n");
      out.write("\t\t\t\talert(\"Please select the isnearest option ! \");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t if (isnewpipeline == '3') {\r\n");
      out.write("\t\t\t\talert(\"Please select the isnewpipeline option !\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t if (estimationCost == null || estimationCost == '') {\r\n");
      out.write("\t\t\t\talert(\"Please Enter the  Estimation Cost !\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t if (tentaiveDate == null || tentaiveDate == '') {\r\n");
      out.write("\t\t\t\talert(\"Please select the TentaiveDate!\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar isFileUploaded =  localStorage.getItem('isFileUploaded');\r\n");
      out.write("\t\tif(isFileUploaded != 'true'){\r\n");
      out.write("\t\t\talert(\"Please upload the File!\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t if(confirm(\"Are you sure want to Submit?\")){\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : \"SendEstimationCost.do\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t//\t'appRef' : appRef,'isnearest':isnearest,'isnewpipeline':isnewpipeline,'isproposal':isproposal,'estimationCost':estimationCost,'tentativeDate':tentaiveDate\r\n");
      out.write("\t\t\t\t'appRef' : appRef,'isnearest':isnearest,'isnewpipeline':isnewpipeline,'isproposal':isproposal,'estimationCost':estimationCost,'gst':gst,'totalAmount':totalAmount,'tentativeDate':tentaiveDate\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\twindow.location.reload();\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t }\r\n");
      out.write(" \r\n");
      out.write("\t}\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\".inspectionDate\").datepicker({\r\n");
      out.write("\t\t\tdateFormat : 'dd-mm-yy',\r\n");
      out.write("\t\t\tchangeMonth : true,\r\n");
      out.write("\t\t\tchangeYear : true,\r\n");
      out.write("\t\t\t//maxDate : new Date(),\r\n");
      out.write("\t\t\tshowOn : \"button\",\r\n");
      out.write("\t\t\tminDate : 0,\r\n");
      out.write("\t\t\tmaxDate : \"+2Y\",\r\n");
      out.write("\t\t\tbuttonImageOnly : true,\r\n");
      out.write("\t\t\tbuttonText : \"Select date\",\r\n");
      out.write("\t\t\tbuttonImage : \"library/img/datepicker.png\",\r\n");
      out.write("\t\t\tshowAnim : \"slideDown\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar count=0;\r\n");
      out.write("   \t $('#clonedDiv').on('click','.addFileId',function(){\r\n");
      out.write("   \t\t  var cloned = $('#fileCloneId').clone();\r\n");
      out.write("   \t\t  cloned.find('input[type=file]').val(\"\");\r\n");
      out.write("   \t\t  cloned.find('img.deleteFileId').remove();\r\n");
      out.write("   \t\t  cloned.attr('id','fileCloneId_'+count++);\r\n");
      out.write("   \t\t  cloned.css({'margin-left': '25px'});\r\n");
      out.write("     \t\t cloned.find('.addFileId').after('<img src=\"library/img/delete.JPG\" width=\"25px\" height=\"25px\" class=\"deleteFileId\"/>');\r\n");
      out.write("   \t\t $('#clonedDiv').append(cloned);\r\n");
      out.write("   \t\t \r\n");
      out.write("   \t\t \r\n");
      out.write("   \t  });\r\n");
      out.write("   \t $('#clonedDiv').on('click','.deleteFileId',function(){\r\n");
      out.write("   \t\t  $(this).parent('div').remove();  \r\n");
      out.write("   \t\t});\r\n");
      out.write("   \t  \r\n");
      out.write("   \t  $(\"#btnSubmit\").click(function (event) {\r\n");
      out.write("   \t\t  event.preventDefault();\r\n");
      out.write("    \t\t var flag = true;\r\n");
      out.write("    \t\t  $('input[name=file]').each(function(){\r\n");
      out.write("    \t\t\t \r\n");
      out.write("    \t\t\t  if($(this).val().length==0){\r\n");
      out.write("    \t\t\t\talert(\"Add File or remove the extra file Upload\");\r\n");
      out.write("    \t\t\t\t  flag = false;\r\n");
      out.write("    \t\t\t\t  localStorage.setItem('isFileUploaded', false);\r\n");
      out.write("    \t\t\t  }\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t  });\r\n");
      out.write("    \t\t  \r\n");
      out.write("   \t\t  if(flag){\r\n");
      out.write("   \t\t\t localStorage.setItem('isFileUploaded', true);\r\n");
      out.write("   \t        var form = $('#uploadFormId')[0];\r\n");
      out.write("   \t        var data = new FormData(form);\r\n");
      out.write("   \t        $(\"#btnSubmit\").prop(\"disabled\", true);\r\n");
      out.write("\r\n");
      out.write("   \t        $.ajax({\r\n");
      out.write("   \t            type: \"POST\",\r\n");
      out.write("   \t            enctype: 'multipart/form-data',\r\n");
      out.write("   \t            url: \"uploadMultipleFileByAdmin.do\",\r\n");
      out.write("   \t            data: data,\r\n");
      out.write("   \t            processData: false,\r\n");
      out.write("   \t            contentType: false,\r\n");
      out.write("   \t            cache: false,\r\n");
      out.write("   \t            timeout: 600000,\r\n");
      out.write("   \t            success: function (response) {\r\n");
      out.write("   \t         \talert(response);\r\n");
      out.write("   \t                $(\"#btnSubmit\").prop(\"disabled\", false);\r\n");
      out.write("\r\n");
      out.write("   \t            },\r\n");
      out.write("   \t        });\r\n");
      out.write("   \t\t  }\r\n");
      out.write("   \t  });\r\n");
      out.write("\t\t $('.loginDialog ').parent('div').css({'width':'450px','top':'500px'});\r\n");
      out.write("\t   \t\t$('.imgClose').click(function(){\r\n");
      out.write("\t   \t\t\t$(this).parents('div.loginDialog').dialog('close');\r\n");
      out.write("\t   \t\t});\r\n");
      out.write("\t\t $('#uploadbtn').click(function(){\r\n");
      out.write("\t   \t\t\t$(\".ui-dialog-content\").dialog(\"close\");\r\n");
      out.write("\t   \t\t\t$( \"#uploadDialog\" ).dialog({ 'width':'450px','modal':'true'});\r\n");
      out.write("\t   \t\t}); \r\n");
      out.write("\t\t $('#uploadbtn').click(function(){\r\n");
      out.write("\t   \t\t\t$(\".ui-dialog-content\").dialog(\"close\");\r\n");
      out.write("\t   \t\t\t$( \"#uploadDialog\" ).dialog({ 'width':'450px','modalr':'true'});\r\n");
      out.write("\t   \t\t}); \r\n");
      out.write("\t\t$('input[name=\"approveBtn\"]').click(function() {\r\n");
      out.write("\t\t\tvar appRef = $(this).attr('id');\r\n");
      out.write("\t\t\t/* var remarks=$(this).closest('tr').find('td:nth-child(8)').find('input[type=\"text\"]').val(); */\r\n");
      out.write("\t\t\tvar appRef = appRef;\r\n");
      out.write("\t\t\talert(appRef);\r\n");
      out.write("\t\t\t//var remarks=\"test\";\r\n");
      out.write("\t\t\tif(confirm(\"Are you sure want to Reject?\")){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\turl : \"eeRejcted.do\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t'appRef' : appRef\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\t\t//$('#successMessage').text(response);\r\n");
      out.write("\t\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\t\twindow.location.reload();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar modal = document.getElementById('id01');\r\n");
      out.write("\r\n");
      out.write("\t// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("\twindow.onclick = function(event) {\r\n");
      out.write("\t\tif (event.target == modal) {\r\n");
      out.write("\t\t\tmodal.style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tvar modalr = document.getElementById('id02');\r\n");
      out.write("\r\n");
      out.write("\t// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("\twindow.onclick = function(event) {\r\n");
      out.write("\t\tif (event.target == modalr) {\r\n");
      out.write("\t\t\tmodalr.style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<table class='table-bordered table table-striped display'\r\n");
      out.write("\tstyle='width: 100%; font-size: 28px;'>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <tr>\r\n");
      out.write("\t\t<td colspan='8'\r\n");
      out.write("\t\t\tstyle='text-align: center; background-color: #FCFCF4; font-size: 17px; height: 10px; color: #800000; font-weight: bold;'>\r\n");
      out.write("\t\t\tAfter Inspection & Payment Estimation</td>\r\n");
      out.write("\t</tr> -->\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan='8'\r\n");
      out.write("\t\t\tstyle='text-align: center; background-color: #FCFCF4; font-size: 17px; height: 10px; color: #800000; font-weight: bold;'>\r\n");
      out.write("\t\t\tAfter Inspection </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"content\" style=\"margin-left: 0px !important\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"inner\">\r\n");
      out.write("\t\t<div class=\"row\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-striped table-bordered table-hover\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"dataTables-example\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--  <th style=\"color:black !important\"></th> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"color: black !important\"><b>App Ref#</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"color: black !important\"><b> Name of\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tCompany</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"color: black !important\"><b>Category Type</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"color: black !important\"><b>Contact Person</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"color: black !important\"><b>Zone#</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"color: black !important\"><b>Correspondence\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tAddress</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"color: black !important\"><b>MLD</b></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"color: black !important\"><b></b></th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--  <th style=\"color:black !important\"></th> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--END PAGE CONTENT -->\r\n");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return;
          out.write('\r');
          out.write('\n');
          out.write('	');
          //  c:otherwise
          org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
          _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
          if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t\t<div id='alertBox' style='display: none;'>\r\n");
              out.write("\t\t\t<h3>No Records found</h3>\r\n");
              out.write("\t\t</div>\r\n");
              out.write("\t\t");

			if (request.getParameter("isSumbitted") != null
							&& "Y".equals(request.getParameter("isSumbitted"))) {
		
              out.write("\r\n");
              out.write("\t\t<script>\r\n");
              out.write("\t\t\t$('#alertBox').show();\r\n");
              out.write("\t\t\t$(\"#alertBox\").dialog({\r\n");
              out.write("\t\t\t\tresizable : false,\r\n");
              out.write("\t\t\t\theight : 115,\r\n");
              out.write("\t\t\t\twidth : \"30%\",\r\n");
              out.write("\t\t\t\tmodal : true,\r\n");
              out.write("\t\t\t\tposition : 'center',\r\n");
              out.write("\t\t\t\ttitle : \"Information\",\r\n");
              out.write("\t\t\t\tcloseOnEscape : false,\r\n");
              out.write("\t\t\t\tdialogClass : \"noclose\",\r\n");
              out.write("\t\t\t\tbuttons : {\r\n");
              out.write("\t\t\t\t\t\"Ok\" : function() {\r\n");
              out.write("\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
              out.write("\t\t\t\t\t}\r\n");
              out.write("\t\t\t\t}\r\n");
              out.write("\t\t\t});\r\n");
              out.write("\t\t</script>\r\n");
              out.write("\t\t<script>\r\n");
              out.write("\t\t\t$('#alertBox').show();\r\n");
              out.write("\t\t\t$(\"#alertBox\").dialog({\r\n");
              out.write("\t\t\t\tresizable : false,\r\n");
              out.write("\t\t\t\theight : 115,\r\n");
              out.write("\t\t\t\twidth : \"30%\",\r\n");
              out.write("\t\t\t\tmodalr : true,\r\n");
              out.write("\t\t\t\tposition : 'center',\r\n");
              out.write("\t\t\t\ttitle : \"Information\",\r\n");
              out.write("\t\t\t\tcloseOnEscape : false,\r\n");
              out.write("\t\t\t\tdialogClass : \"noclose\",\r\n");
              out.write("\t\t\t\tbuttons : {\r\n");
              out.write("\t\t\t\t\t\"Ok\" : function() {\r\n");
              out.write("\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
              out.write("\t\t\t\t\t}\r\n");
              out.write("\t\t\t\t}\r\n");
              out.write("\t\t\t});\r\n");
              out.write("\t\t</script>\r\n");
              out.write("\t\t");

			}
		
              out.write('\r');
              out.write('\n');
              out.write('	');
              int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- PAGE LEVEL SCRIPTS -->\r\n");
      out.write("<script src=\"assets/plugins/dataTables/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"assets/plugins/dataTables/dataTables.bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"assets/plugins/dataTables/jquery.dataTables.js\"></script>\r\n");
      out.write("    <script src=\"assets/plugins/dataTables/dataTables.bootstrap.js\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("         $(document).ready(function () {\r\n");
      out.write("             $('#dataTables-example').dataTable();\r\n");
      out.write("         });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"loginDialog\" id=\"uploadDialog\" style=\"display: none;\">\r\n");
      out.write("<img class=\"imgClose\" src=\"library/img/Close_SMS.png\" style=\"width:40px;border-width:0px;float: right; margin-top: -42px; margin-right: -5px; cursor: pointer;\">\r\n");
      out.write("\t\t<table width=\"100%\" align=\"center\"><tr><td align=\"center\">\t\r\n");
      out.write("\t<form id=\"uploadFormId\" method=\"POST\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<br/><br/>\r\n");
      out.write("\t\t<div id=\"clonedDiv\">\r\n");
      out.write("\t\t<div id=\"fileCloneId\" >\r\n");
      out.write("\t\t<input type=\"file\" name=\"file\" accept=\".doc,.docx,.dwg,.pdf,.txt,.xlsx,.xls\"><img src=\"library/img/add.JPG\" width=\"25px\" height=\"25px\" class=\"addFileId\"/><br /> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"appId\" id=\"appId\" value=''><br /> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"submit\" id=\"btnSubmit\" value=\"Upload\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</td></tr></table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(554,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/JSP/Application/eeafterInsp.jsp(554,9) '${list.appBean}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list.appBean}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(554,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("app");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"odd gradeX\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"EEViewForm.do?appId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getAppId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" style=\"color: rgb(128,128,128)\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getAppId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getLegCompName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getCategoryType()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getContactPersonName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\"></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getCdoorNo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getCplotNo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getCstreetName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getClocation()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" }</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\"></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td><button onclick=\"getPaymentDetails(this.id)\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"paymentClass\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getAppId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: auto;\">Forward</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button onclick=\"EERejected(this.id)\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"cancelbtn\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getAppId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: auto;\">Rejected</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"imgcontainerr\">\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<table id=\"id02\" class=\"modalr\" style=\"display: none;\">\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr height=\"20px\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: #1589FF; color: white; font-weight: bold;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\" align=\"center\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 0px !important\">Estimation Cost\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tForm <span\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"document.getElementById('id02').style.display='none'\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"popupclose\" title=\"Close Modalr\">&times;</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label><b>Remarks </b></label></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"textarea\" width=\"100%\" height=\"30px\" name=\"txtremarks\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"txtremarks\" placeholder=\"EX: Comments\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=\"2\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button onclick=\"eeReject(this.id)\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"paymentClass\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getAppId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: auto;\">Submit</button>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\r\n");
          out.write("\t\t\t<div class=\"imgcontainer\">\r\n");
          out.write("\r\n");
          out.write("<input type=\"hidden\" id=\"estCostAppId\" value=\"\"/>\r\n");
          out.write("<input type=\"hidden\" id=\"rejectAppId\" value=\"\"/>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<table id=\"id01\" class=\"modal\" style=\"display: none;\">\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr height=\"30px\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: #1589FF; color: white; font-weight: bold;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\" align=\"center\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 0px !important\">Estimation Cost\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tForm <span\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"document.getElementById('id01').style.display='none'\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"popupclose\" title=\"Close Modal\">&times;</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label><b>Whether water connection will be given directly from the\r\n");
          out.write("nearest Transmission/Distribution main</b></label></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><select class=\"lessWidth\" id=\"isnearest\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"isnearest\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">--Select--</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Yes</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\">No</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label><b>Whether tendering for new pipeline Required</b></label></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!--  <input type=\"password\" placeholder=\"Enter Password\" name=\"psw\" required> -->\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"lessWidth\" id=\"isnewpipeline\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"isnewpipeline\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">--Select--</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">Yes</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\">No</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label><b>Estimation Cost (Rs) </b></label></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"txtestpayment\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"txtestpayment\" placeholder=\"Ex: 4,00,000\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonkeypress='return event.charCode >= 48 && event.charCode <= 57' onkeyup=\"gst(txtestpayment)\" >\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<br></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label><b>GST Rs (18 %) </b></label></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"gst\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"gst\"  readonly placeholder=\"Ex: GST @ 18 %\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonkeypress='return event.charCode >= 48 && event.charCode <= 57'>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<br></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label><b>Total Cost (Rs) </b></label></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"totalAmount\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"totalAmount\" readonly placeholder=\"Ex: 24,00,000\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonkeypress='return event.charCode >= 48 && event.charCode <= 57'>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<br></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><label><b>Tentative Connection Date</b></label></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"remarks\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"tentaiveDate\" readonly placeholder=\"dd-mm-yyyy\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"inspectionDate\" style=\"width: 130px !important;\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" /></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=\"2\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"uploadbtn\" id=\"uploadbtn\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: auto;\">Upload Inspection report</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button onclick=\"SendEstimationCost(this.id)\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"paymentClass\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${app.getAppId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: auto;\">Submit</button>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div></td>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(750,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty list.results}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t\t<table\r\n");
        out.write("\t\t\tclass='jDataTable table-bordered table tabel-striped bootstrap-datatable display'\r\n");
        out.write("\t\t\tid='tblSearchcomplaintTable'>\r\n");
        out.write("\t\t\t<thead>\r\n");
        out.write("\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t<th>");
        if (_jspx_meth_spring_005fmessage_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
          return true;
        out.write("</th>\r\n");
        out.write("\t\t\t\t\t<th>");
        if (_jspx_meth_spring_005fmessage_005f1(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
          return true;
        out.write("</th>\r\n");
        out.write("\t\t\t\t\t<th style='min-width: 150px;'>");
        if (_jspx_meth_spring_005fmessage_005f2(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
          return true;
        out.write("</th>\r\n");
        out.write("\t\t\t\t\t<th>");
        if (_jspx_meth_spring_005fmessage_005f3(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
          return true;
        out.write("</th>\r\n");
        out.write("\t\t\t\t\t<th>");
        if (_jspx_meth_spring_005fmessage_005f4(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
          return true;
        out.write("</th>\r\n");
        out.write("\t\t\t\t</tr>\r\n");
        out.write("\t\t\t</thead>\r\n");
        out.write("\t\t\t<tbody>\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t</tbody>\r\n");
        out.write("\t\t</table>\r\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(757,9) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f0.setCode("label.complaintNumber");
    int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
      if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(758,9) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f1.setCode("label.channel");
    int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
      if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(759,35) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f2.setCode("label.recievedDateTime");
    int[] _jspx_push_body_count_spring_005fmessage_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f2 = _jspx_th_spring_005fmessage_005f2.doStartTag();
      if (_jspx_th_spring_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f2.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f3 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(761,9) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f3.setCode("label.content");
    int[] _jspx_push_body_count_spring_005fmessage_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f3 = _jspx_th_spring_005fmessage_005f3.doStartTag();
      if (_jspx_th_spring_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f3.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f4 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(762,9) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f4.setCode("label.status");
    int[] _jspx_push_body_count_spring_005fmessage_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f4 = _jspx_th_spring_005fmessage_005f4.doStartTag();
      if (_jspx_th_spring_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f4.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(766,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/JSP/Application/eeafterInsp.jsp(766,4) '${list.results}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list.results}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(766,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("results");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t<form method='post' id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${results.getComplaintID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\t\t\taction=\"editComplaint.do\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<input type='hidden' name=\"complaintID\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${results.getComplaintID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" /> <a\r\n");
          out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:fnSubmitForm('");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("');\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${results.getComplaintNumber()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\r\n");
          out.write("\t\t\t\t\t\t\t</form>\r\n");
          out.write("\t\t\t\t\t\t</td>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${results.getComplaintSourceName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${results.getCreatedDate()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${results.getComplaintContent()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${results.getComplaintStatusName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/JSP/Application/eeafterInsp.jsp(773,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${results.getComplaintID()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
